### ISSUE TITLE
Support a list of errors

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#106]
zod can return a list of errors for a single field. It would be nice if conform could handle this case and the error for a field could be an array of error messages. An example would be a password field that has multiple requirements.

**Comment by brandonpittman** [comment]
I believe this is covered by https://github.com/edmundhung/conform/pull/96.

**Comment by edmundhung** [comment]
As @brandonpittman mentioned, this is already implemented on #96 which is not released yet. You can see some examples code including zod on the PR.

I am still writing docs for all the changes but you can expect a new release coming on the next 2 days.

**Comment by edmundhung** [comment]
This feature is released on [v0.6.0](https://github.com/edmundhung/conform/releases/tag/v0.6.0).
