### ISSUE TITLE
Handle checkboxes with Zod?

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#107]
Does conform do anything to coerce a checkbox to a boolean when using a Zod schema?

**Comment by brandonpittman** [comment]
I don't believe so.

**Comment by edmundhung** [comment]
Conform does not coerce anything as there is no easy way to determine if the form data was set with a checkbox from the server.

You can set it up as `z.string().transform(value => value === 'on')` or `z.preprocess(value => value === 'on', z.boolean())` based on your preference.

**Comment by edmundhung** [comment]
You can now use `z.boolean()` for required checkbox and `z.boolean().optional()` for optional checkbox from [v0.8.0](https://github.com/edmundhung/conform/releases/tag/v0.8.0).

**Comment by kentcdodds** [comment]
Sweet!

**Comment by luanfonsecap** [comment]
How can i validate if at least one checkbox is checked? Any suggestions?

**Comment by edmundhung** [comment]
@luanfonsecap It sounds like you are validating a list of checkboxes. In this case I will define a string array schema with a [nonEmpty](https://zod.dev/?id=nonempty) check.

**Comment by binajmen** [comment]
> @luanfonsecap It sounds like you are validating a list of checkboxes. In this case I will define a string array schema with a [nonEmpty](https://zod.dev/?id=nonempty) check.

But if you only select one checkbox, it becomes a string instead of an array of one value 🤔

**Comment by edmundhung** [comment]
Yep. It will be a string instead of an array of there is only 1 item. But it should work fine because of the automatic type coercion feature with zod which will transform it to an array before validating it.

**Comment by timzolleis** [comment]
Is there an option to use `z.boolean` inside nested objects? Lets say I have:
```ts
const schema = z.object({
  entries: z.array(z.object({
    secret: z.boolean().optional()
  })
})
```
 Which does not transform the checkboxes to booleans (even though they have the correct name) - im using it with "transform" right now. Is this a know bug or by design?

**Comment by edmundhung** [comment]
@timzolleis It might be related to #391 if you have no other text inputs inside the object.

**Comment by artursopelnik** [comment]
I'm using this, like the following:

```typescript
const NON_EMPTY_MESSAGE = "please check this field"
z.boolean(NON_EMPTY_MESSAGE).refine((val) => val === true, {
    message: NON_EMPTY_MESSAGE
})
```
