### ISSUE TITLE
"Repeated field name is not supported" when using checkbox

### ISSUE THREAD

**Issue by augustskare** [edmundhung/conform#112]
Implementing a form where I have multiple `<input type="checkbox" />` that share the same name, but getting the error "Repeated field name is not supported". Can't find anything in the documentation if I need to treat checkboxes differently. Do I need to do that? When not using conform I would get the values with `formData.getAll("name")` and get an array back of all the checked inputs.

**Comment by edmundhung** [comment]
Hi @augustskare. To support a list of checkbox, you can use the `useFieldList()` API like this:
```tsx
function Example() {
  const [form, { options }] = useForm();
  const [checkbox1, checkbox2, checkbox3] = useFieldList({
    ...options.config,
    // If you want to have a fixed list of 3 checkboxes 
    defaultValue: options.config.defaultValue ?? Array.from(3),
  });

  return (
    <form>
      <input {...conform.input(checkbox1.config, { type: 'checkbox' })} />
      {checkbox1.error}
      <input {...conform.input(checkbox2.config, { type: 'checkbox' })} />
      {checkbox2.error}
      <input {...conform.input(checkbox3.config, { type: 'checkbox' })} />
      {checkbox3.error}
    </form>
  )
}  
```

I understand browsers support inputs with the same name natively. But this conflicts with a server first solution which needs an unique name to map each error to the corresponding input. I have considered some hacky approach to get around this issue before, but it gets more complicated as Conform also support nesting with its naming convention. (e.g. The result of `[['options[0]', 'on'], ['options[1]', 'on']]` is the same as `[['options', 'on'], ['options', 'on']]`).

I hope this answer your question. I will keep this issue open until it is documented :)

**Comment by augustskare** [comment]
I see, that makes sense! Documentation is hard, keep up the good work 💯 Really enjoying conform 🥇

**Comment by danestves** [comment]
I'm getting this error when I provide a custom ID to the `useForm` hook that is not with the `useId` hook from `react`, notice that I'm not using any checkbox in my code, just put the ID `lesson-actions` and that trigger that warning and the form is not executed. If I switch back to `useId` everything works as expected

**Comment by edmundhung** [comment]
Hi @danestves. Can you double check if the id `lesson-actions` is unique on the page? Conform search for fields within a form using [HtmlFormElement.elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements). If you have any form controls outside of the form but linked using the form attribute, it will still be counted.

**Comment by edmundhung** [comment]
Reopen at it is not documented still 😅

**Comment by vcheeze** [comment]
@edmundhung thanks for the good work on Conform. I have a similar use case, but the checkboxes are dynamic (fetched from an API based on some user input within the same form). Is there any way to implement this scenario with Conform?

**Comment by edmundhung** [comment]
Conform [v0.8.0](https://github.com/edmundhung/conform/releases/tag/v0.8.0) supports checkbox groups now. Check the [guide](https://conform.guide/checkbox-and-radio-group) for details.
