### ISSUE TITLE
CSS :valid selector with zod

### ISSUE THREAD

**Issue by msfleischer** [edmundhung/conform#123]
Is there a way to get the CSS `:valid` selector to only be active after the initial submission using zod? For example in [this sandbox](https://codesandbox.io/s/interesting-tereshkova-r71i84?file=/app/routes/_index.tsx), the `:valid` selector is already active before the form has been submitted, but ideally it would only show after it passes client-side validation after initial submission.

**Comment by edmundhung** [comment]
Hi @msfleischer, this is a limitation from the browser unfortunately. There is an experimental css selector named [:user-invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid) that tries to address this. But I also have concern on the progressive enhancement aspect as the browser will not know the full error before JS is loaded.

I would suggest continue using a class-based approach especially if you are building with Remix.

**Comment by msfleischer** [comment]
Ah, that actually makes sense. Thanks for the help on that.
