### ISSUE TITLE
Form is being submitted on each keypress after an error occurs

### ISSUE THREAD

**Issue by m0t0r** [edmundhung/conform#125]
**Description**
Steps:
- Have a basic form which has validations
- Submit the form with invalid values
- Get an error response
- Try to re-enter values and observe form is being submitted on each keypress

Version: 0.6.0

Repro: https://codesandbox.io/s/brave-lamarr-6s9zbg?file=/app/routes/login.tsx to better observe the issue, open browser window in a new tab and see logs from `onSubmit` when you type new value after an error.

**Actual**
Form is unexpectedly submitted on each keypress after an error

**Expected**
Form should be submitted only when clicking on a submit button

**Comment by edmundhung** [comment]
Hi @m0t0r. Sorry for the confusion. This is actually a feature on Conform called **server validation** which validates with the server. But I probably should have the basic example setup with client validation which people are more familiar with.

In your example, there is no validation logic defined on the client and so Conform fallbacks to server validation. After the first submission, it also re-validates when you try to update the value again.

You can enable client validation by providing an `onValidate` handler:
```tsx
const [form, { email, password, confirmPassword }] = useForm<SignupForm>({
    // Sync the result of last submission
    lastSubmission,

    // This setup validation on the client and
    // Conform will not validate it with the server, unless
    // there is any exception thrown during the validation (fallback) 
    onValidate: ({ formData }) => parseFormData(formData),

    // The onSubmit handler will only be called when you click the submit button now
    onSubmit: () => {
        console.log("onSubmit called!");
    }
});
```

You can find more information on different validation mode [here](https://conform.guide/validation).

**Comment by m0t0r** [comment]
@edmundhung thanks for you reply. Is there a way to validate on a server but only when submit button is pressed ? I don't want to make a ton of requests to the API on each keypress and I also would like to have only server validation?

**Comment by edmundhung** [comment]
What you want is disabling the auto revalidation behaviour. Unfortunately, this is not possible yet. 😅 But I can implement it during the weekend. It is also on my todo list for a while anyway.

**Comment by edmundhung** [comment]
You can now customize when Conform should re-validate using the new `shouldRevaldiate` config. Check the [release note](https://github.com/edmundhung/conform/releases/tag/v0.6.1) for more details.
