### ISSUE TITLE
What is the difference between "shouldRevalidate" and "shouldValidate"?

### ISSUE THREAD

**Issue by khabubuphathu** [edmundhung/conform#134]
I have updated to the latest version and I am confused between "shouldRevalidate" and "shouldValidate" as I want conform to validate onChange which I think has now become "onInput".

When shouldValidate is set to onInput it clears the global form error. Is this expected?

**Comment by edmundhung** [comment]
Yes. The config is renamed to onInput to reflect which event Conform is actually listen to. The behaviour should stay the same if you were setting it to onChange.

It is expected if your form error comes from the server. But if you are not, i can think of a problem from zod that might affect this. Please share your zod schema if you think it is relevant.

**Comment by edmundhung** [comment]
Feel free to reopen it if needed.
