### ISSUE TITLE
Reset list to empty array?

### ISSUE THREAD

**Issue by gmencz** [edmundhung/conform#142]
Is it possible to reset a list to an empty array (the default value for my use case) in an imperative way? I was looking at the `list` helper but it does not have a function for that and calling `requestIntent` multiple times in a loop doesn't seem to work.

**Comment by edmundhung** [comment]
Hi @gmencz. So you want a way to remove all list item (or reset the list) without resetting the rest of the form, right?

I just tried the following snippet and it works for me. 
```
Array.from(Array(itemsList.length)).forEach(() => {
  // Delete the first item everytime
  requestIntent(formElement, list.remove(items.name, { index: 0 }));
});
```

I would love to know more about your usecase. The solution above will trigger a re-render each time and is definitely not ideal. An alternative solution could be adding support of removing all items without specifying an index, e.g. `list.remove(items.name)` or a reset e.g. `list.reset(items.name)`.

**Comment by gmencz** [comment]
@edmundhung Oh that's interesting, it wasn't working for me because I was passing the index on each iteration rather than 0 but now that I think about it, it makes sense.

My use case is the following, I have 2 selects on my form, the possible options you can select on select number 2 (this select allows you to select multiple options) depends on what you selected on select number 1 so imagine the following scenario:

User selects option X on select number 1 which leads to select number 2 being enabled and showing you some options, now the user selects some options from select number 2. Now the user selects a different option on select number 1 which now makes the options they selected for select number 2 no longer valid and now I would want to reset the array because the possible valid options have changed.

**Comment by Pouet--** [comment]
Hello there,

I am very interested in a feature like `list.remove(items.name)`  to remove all items in one go and `list.reset(items.name)`   to reset the list to its initial value.

My usecase is a list of filters to apply to a table. This is a nested object, to which you can add children in an infinite way.
Removing a node with an index works well, but resetting or empty the list would be very useful.

**Comment by edmundhung** [comment]
We have introduced a new `reset` intent that could be apply to any field. Checkout the docs here: https://conform.guide/intent-button
