### ISSUE TITLE
Clear the errors

### ISSUE THREAD

**Issue by danestves** [edmundhung/conform#143]
Is there a way to clear the errors using any utility? I'm currently having a product request to make a functionality like this but couldn't figure it out yet

**Comment by edmundhung** [comment]
Hi @danestves. Will `formElement.reset()` works? Or if you are trying to "hide" the errors?

**Comment by edmundhung** [comment]
What is your usecase? To clear all errors, one way I can think of now is to use a custom intent and have the parser returns a submission with no error whenever it sees that intent. But all errors will come back once it revalidates.

**Comment by danestves** [comment]
> What is your usecase? To clear all errors, one way I can think of now is to use a custom intent and have the parser returns a submission with no error whenever it sees that intent. But all errors will come back once it revalidates.

I have some checkboxes to accept the terms, when the user doesn't check anything and click on submit the errors appear, until here is perfect; the client wants that when the user checks a checkbox the error disappear, but if he unchecks again the error doesn't appear until he hit the submit button (I'm using the validations on submit)

**Comment by edmundhung** [comment]
I think Conform is quite limited on this aspect and probably need to be improved 😅 For now, I see 2 solutions: 
(1) Just make an additional state to hide the error you want, or 
(2) Opt-out from Conform revalidation (i.e. `shouldRevalidate: 'onSubmit'`) and customize the revalidation behaviour yourself. This means setting up an input / blur handler yourself and call `requestIntent(form, validate(fieldName))` only when appropriate.

**Comment by danestves** [comment]
Yeah, actually I'm kind of angry with the requirement because that's a tricky behavior, and I'm going to put that ticket on my team as blocked until they reviewed more. Thanks for the answers and we can close this ticket!

**Comment by edmundhung** [comment]
All good. Let me know if you need an example especially for solution 2. I have been rethinking about the error handling recently and this reminds me what I should also covered for the new design. Thanks for the question!
