### ISSUE TITLE
Upgrading to 0.6.2 changes validation behavior

### ISSUE THREAD

**Issue by brandonpittman** [edmundhung/conform#150]
I'll try to debug and write this up more fully in the morning, but after upgrading to `0.6.2`, one of my forms passes validation after any change, even when there are invalid fields. Reverting to `0.6.1` restores expected behavior.

**Comment by brandonpittman** [comment]
I'm logging the value returned by `onValidate`:

<img width="513" alt="CleanShot 2023-05-23 at 9 57 44@2x" src="https://github.com/edmundhung/conform/assets/967145/cc4553a3-10c3-43ed-b81d-00c6858fad84">

Even though there are two errors, it's moving on to submission.

**Comment by edmundhung** [comment]
This is fixed on [v0.6.3](https://github.com/edmundhung/conform/releases/tag/v0.6.3).
