### ISSUE TITLE
Can't useFieldset on zod optional object

### ISSUE THREAD

**Issue by baker-travis** [edmundhung/conform#151]
When creating a zod schema containing an optional object, I am unable to use `useFieldset` on it because the field config for it is possibly undefined. I would expect the field config to always be there, and only have the validation handle the optional part of it.

Example schema:
```js
const schema = z
  .object({
    email: z
      .string()
      .min(1, "Email is required")
      .email("Please enter a valid email"),
    address: z
      .object({
        street1: z.string().min(1, "Street 1 is required"),
        street2: z.string().min(1).optional(),
        city: z.string().min(1, "City is required"),
        state: z.string().min(1, "State is required"),
        postalCode: z.string().min(1).max(5),
      })
      .optional(),
  })
```

`address` would come back as type `FieldConfig<{street1: string, street2?: string, ...}> | undefined`, meaning I couldn't pass it to `useFieldset`.

Example code sandbox: https://codesandbox.io/p/sandbox/peaceful-mclean-g1mygf?file=%2Fapp%2Froutes%2Findex.tsx%3A8%2C1-28%2C5

See `routes/index.tsx:67`

**Comment by edmundhung** [comment]
Thanks for the bug report @baker-travis! It should be fixed now on [v0.6.3](https://github.com/edmundhung/conform/releases/tag/v0.6.3).
