### ISSUE TITLE
How to validate objects?

### ISSUE THREAD

**Issue by jonathanpalma** [edmundhung/conform#155]
I am migrating a small code base from `react-hook-form` to `coform`

So, I am wondering how can I validate the prop `service` from the following schema:

<img width="549" alt="image" src="https://github.com/edmundhung/conform/assets/12414771/7d42041c-44db-46fb-8602-91cd38b26dc1">

As you can see, the values are present in the form submission.

<img width="340" alt="image" src="https://github.com/edmundhung/conform/assets/12414771/81d9e95e-51e0-4710-b5aa-7dc9d0608f49">

As a reference I am using Listbox (Select) from Headless UI

https://headlessui.com/react/listbox#using-with-html-forms

**Comment by jonathanpalma** [comment]
https://codesandbox.io/p/sandbox/remix-object-field-validation-t06fut

**Comment by jonathanpalma** [comment]
https://codesandbox.io/p/sandbox/remix-object-field-validation-t06fut

**Comment by edmundhung** [comment]
Hi @jonathanpalma,

Here is an [example](https://codesandbox.io/p/sandbox/conform-select-object-qozstb) based on the Listbox from Headless UI.

Generally I would avoid passing an object but just the identity only which is the source of truth. But if there is a need to pass an object, one approach would be stringify it as json and have zod preprocess it using `JSON.parse()`. It might be tempting to recreate the structure using a set of hidden inputs, but they will be serialized as formData and you will lost the type information (as everything will become string) which requires additional effort to cast the type of each property manually.

In case you missed it, you can also find examples integrating with other Headless UI component [here](https://conform.guide/examples/headless-ui)
