### ISSUE TITLE
Support multiple values for a field ?

### ISSUE THREAD

**Issue by iammemon** [edmundhung/conform#163]
I couldn't find any example of handling multiple values for a field. A common example would be a custom element with multiple select options. what's the recommended way to handle this case?

**Comment by edmundhung** [comment]
Hi @iammemon,

Here is an [example](https://codesandbox.io/p/sandbox/conform-select-object-forked-um8mlg?file=%2Fsrc%2FApp.tsx%3A124%2C17) using the Headless UI Listbox. This is done by stringify-ing the array as json and have zod preprocess it using JSON.parse(). It might be tempting to recreate the structure using a set of hidden inputs, but they will be serialized as formData and you will lost the type information (as everything will become string) which requires you to cast the type manually as well.

FYI, if you are using a native multiple select, then you can pass the props directly similar to a native input:
```tsx
<select {...conform.select(fields.items)} multiple>
  <option>A</option>
  <option>B</option>
  <option>C</option>
</select>
```

**Comment by iammemon** [comment]
Hey @edmundhung thanks for the example that helps
