### ISSUE TITLE
Remix example for signup is not working

### ISSUE THREAD

**Issue by jansedlon** [edmundhung/conform#166]
Hi!

I noticed that the remix example for [signup](https://codesandbox.io/s/github/edmundhung/conform/tree/main/examples/remix?from-embed=&file=/app/routes/signup.tsx) is not working. When I enter everything correctly, it won't sign up the form.

It might have to do something with the `useForm` hook. Even if everything is correct, it still falls into the `if` condition.
<img width="610" alt="image" src="https://github.com/edmundhung/conform/assets/13948180/a4de4d91-df93-4363-8e00-0f6e60981235">

**Comment by edmundhung** [comment]
@jansedlon Thanks for pointing it out. I am surprised the test suite didn't catch this. 😅 I will put up a patch later today.

**Comment by jansedlon** [comment]
I patched the package with your PR and it works, many thanks 🎉
