### ISSUE TITLE
add support for zod error map

### ISSUE THREAD

**Issue by tomer-yechiel** [edmundhung/conform#174]
https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#customizing-errors-with-zoderrormap

**Comment by edmundhung** [comment]
Hi @tomer-yechiel,

Can you help me understand what's not working at the moment? I haven't try the error map personally. But, by looking at the [example](https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#a-working-example), I can't see why this is not supported yet.

FYI, the Zod integration is just looping over all errors on the `ZodError` and then construct the error object based on the message and path as shown [here](https://github.com/edmundhung/conform/blob/main/packages/conform-zod/index.ts#L184-L198).

**Comment by edmundhung** [comment]
Ah, I see. Thanks for explaining! Happy to have this supported. I can work on it over the weekend but feel free to submit a PR if you wanna give it a try 👍🏼

**Comment by tomer-yechiel** [comment]
Awesome, thanks!
