### ISSUE TITLE
Forward slash in default value with list doesn't work

### ISSUE THREAD

**Issue by iammemon** [edmundhung/conform#181]
When I use a string that contains a forward slash as a default value with a list method like `append` or `replace`.  It triggers the validations for the whole form. If there are no validation errors it doesn't work.

```
 <button
        {...list.append(tasks.name, {
          defaultValue: { content: "Random /  More Random" },
        })}
      >
        Add task
</button>
```

**Comment by edmundhung** [comment]
This should be fixed on [v0.7.0](https://github.com/edmundhung/conform/releases/tag/v0.7.0). Thanks!
