### ISSUE TITLE
Reset doesn't work after first submission using new method

### ISSUE THREAD

**Issue by Mattinton** [edmundhung/conform#191]
Hey,

Really enjoying using conform. Just trying out the new reset method in v0.7.0 and can't get it to work, after the second submission it won't reset.

Here is a minimal example: https://codesandbox.io/p/sandbox/jovial-field-h3qckx?embed=1&file=%2Fapp%2Froot.tsx%3A43%2C18

If you submit a value in the text box it will be cleared the first time, afterwards it won't get cleared if you try another input.

Pretty sure it's something to do with passing in the last submission, and probably a useEffect or something under the hood not being updated with new deps.

**Comment by edmundhung** [comment]
Hi @Mattinton, I am glad you like it :)

Thanks for the report! I overlooked the situation after the first reset happen. If the submission has been successful consecutively, the internal useEffect call will not be executed as it is still receiving the same null value and thus no reset happens.

Here is a PR (#194) with an alternative solution.

**Comment by Mattinton** [comment]
Hey, thanks for coming back to me so fast. Looked over the PR, that'll do the trick!

Looking forward to it getting merged 😄

**Comment by edmundhung** [comment]
Fixed on [v0.7.2](https://github.com/edmundhung/conform/releases/tag/v0.7.2).
