### ISSUE TITLE
Allowing different error types than a string

### ISSUE THREAD

**Issue by jbovenschen** [edmundhung/conform#198]
Thank you for this use-full library.

This issue is related to https://github.com/edmundhung/conform/discussions/187, where there is a discussion going on related to i18n. I'm currently working in a project which supports over 40 different locales and really wan't  to be able to use this library. The thing which is currently blocking me is that I need to return errors which look like `{ id: 'validation.minLength', values: { minValue: 12 } }` which can be passed to the internationalisations library. I've been exploring the library and the place where it stops working (ignoring the typescript errors) is the `useForm` hook. This seems to enforce the errors to be a string, didn't yet figure out where it happens, but do you see problems in allowing the errors to be of another type than a string?

**Comment by edmundhung** [comment]
Hi @jbovenschen,

If I understand what you mentioned in the discussion correctly, are you concerning if a user switch the language when some error messages are populated already with solution 2/3?

Unfortunately this is currently not possible as the setup enforce string only. The only way to get closer to what you want is to serialize the data as json (so it becomes a string) and then parse it on the client before translation.

I think that's a valid request so I would definitely revisit this soon.

**Comment by jbovenschen** [comment]
> If I understand what you mentioned in the discussion correctly, are you concerning if a user switch the language when some error messages are populated already with solution 2/3?

Yes, what I mean in the discussion is that for option 2 or 3 there is a connection between the loader (back-end) and internationalisation (front-end), this would mean if we want to show the error messages in the language of the user we need to reload the page and "undo" the work the user was doing. It's kind of an edge case but would be nice if it could been avoided. 

> Unfortunately this is currently not possible as the setup enforce string only. The only way to get closer to what you want is to serialize the data as json (so it becomes a string) and then parse it on the client before translation.

Yes, this is how we currently try to solve it, but it would be nice if we didn't need to that because then it would be possible to be typesafe in what we're returning from the loaders. But also there is some overhead involved which would be nice to avoid.

> I think that's a valid request so I would definitely revisit this soon.

Great thank you for the response.

**Comment by edmundhung** [comment]
This is now possible with the `formatError` option on the [parseWithZod](https://conform.guide/api/zod/parseWithZod) helper.
