### ISSUE TITLE
Please use proper semver

### ISSUE THREAD

**Issue by meza** [edmundhung/conform#204]
Hey,

A lot of us depend on automated tools for dependency updates. They all work trusting that everything conforms to the semver standard.

In this case, anything with breaking changes should be a major version bump.

This should've made it 1.0.0
<img width="180" alt="image" src="https://github.com/edmundhung/conform/assets/211977/fffdf2fc-5c09-47ec-938a-00cb413a8862">

I know that sometimes we attach some magical meaning to a 1.0 release. While that might work for game development, it's definitely not useful for library releases.

I highly recommend using [Semantic Release](https://github.com/semantic-release/semantic-release) together with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) to automate the process and you'll never have to worry about it ever again.

I'm happy to help with setting it up,

**Comment by edmundhung** [comment]
Hi @meza. The current versioning does satisfy how NPM handles package version. 
 
I would suggest you trying this [calculator](https://semver.npmjs.com/) that demonstrate how NPM handles version range. For example, you can set package name to `@conform-to/react` with the Version range as `^0.6.0`. The result will include 4 versions only: `0.6.0`, `0.6.1`, `0.6.2`, `0.6.3`. Another example could be [react](https://www.npmjs.com/package/react?activeTab=versions) which has been using the zero major version until 15.

I hope this address your concern. :)
