### ISSUE TITLE
Default ariaAttributes to true

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#213]
If you're using `{...form.props}` that has the aria attributes. If I'm using `{...conform.input(field)}` that does not have the aria attributes. I have to enable those with `ariaAttributes: true` which I find confusing/surprising.

Could we default that to true please? Most of the time people should be rendering those things.

**Comment by edmundhung** [comment]
I was concerning if people are using it with custom inputs that already manages aria attributes and it might cause conflicts if it is default to true. But, now I am thinking about this again, the custom inputs should either ignore them if they don't support setting the aria attributes or else manage to merge the props correctly. I will change the default on the next version.

**Comment by kentcdodds** [comment]
That sounds great to me!

**Comment by edmundhung** [comment]
Fixed on [v0.8.0](https://github.com/edmundhung/conform/releases/tag/v0.8.0).

**Comment by kentcdodds** [comment]
Terrific 👏
