### ISSUE TITLE
Make `acceptMultipleErrors: () => true` the default

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#215]
Let's say we have a password input that has 6 validation rules. As a user it would really me if an app only shows one error message at a time. I fix it and submit the form and now I have another error to deal with. Six times! That would be super annoying. I'd much rather see *all* the error messages and fix them all in one go.

I understand if some folks would prefer to have a single error message at once in some cases, but I consider that to be the exception. Thoughts?

**Comment by edmundhung** [comment]
Fixed on [v0.8.0](https://github.com/edmundhung/conform/releases/tag/v0.8.0).

**Comment by kentcdodds** [comment]
👏👏
