### ISSUE TITLE
Pain point: adding list.append/list.remove takes over [Enter] form submission

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#216]
Here's a form UI I have:

<img width="599" alt="image" src="https://github.com/edmundhung/conform/assets/1500684/c77a2478-8b39-4c18-8428-61066ab2a508">

Before adding the list.append (the + Image button) and list.remove (the x button), hitting the [ENTER] key on the title input would submit the form, but once I added the list buttons, hitting the [ENTER] key on the title input submits the list.remove button because it's a submit button that appears first within the form. This is surprising and for some it could be confusing as well.

The workaround I've come up with is adding `<button type="submit" className="hidden" />` as the first child to the form. This works, but I wonder if there's a better solution or perhaps a utility conform could expose that would make this an implementation detail people don't have to think about.

**Comment by edmundhung** [comment]
As stated on the [spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission):

> A [form](https://html.spec.whatwg.org/multipage/forms.html#the-form-element) element's default button is the first [submit button](https://html.spec.whatwg.org/multipage/forms.html#concept-submit-button) in [tree order](https://dom.spec.whatwg.org/#concept-tree-order) whose [form owner](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-owner) is that [form](https://html.spec.whatwg.org/multipage/forms.html#the-form-element) element.

Manually adding a submit button at the top of the form seems to me the only solution for now.
```html
<form>
  <button type="submit" hidden />
  <!-- .... -->
</form>
```

Conform might be able to render the extra button for you if it has a Form component in the future, but I am also concern if you need custom intent on the default submit button.  Rendering an extra element before the children of the form element will be confusing with styling too.

**Comment by kentcdodds** [comment]
Yep, those are my concerns as well. I'm not sure if there's anything Conform *should* do about this. It's probably just something people should consider whenever they add another button 🤷‍♂️
