### ISSUE TITLE
Introspect the Zod schema to make array inputs always arrays

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#219]
There's this caveat in the form guide:

> Conform will transform the value to an array only when there are more than one files selected. To ensure a consistent data structure, you need to preprocess the data as shown in the snippet.

I would like it very much if Conform were to introspect the Zod schema for this. If I expect something to be an array, turn it into one even if only one value was submitted. I did this in my own version of the parser and it was annoying but it worked well: https://github.com/epicweb-dev/rocket-rental/blob/a85622e0539b84f2ff06f4c9aee472e328f9052e/app/utils/forms.tsx#L340

**Comment by edmundhung** [comment]
Hey @kentcdodds, I would like to know how you feel about #230. Just check the diff and you will see how it is implemented and what it achieved.

I still have mixed feeling on introspecting zod schema but this pretty much removes all transform step devs will ever needed. 😅

**Comment by edmundhung** [comment]
Fixed on [v0.8.0](https://github.com/edmundhung/conform/releases/tag/v0.8.0).

**Comment by kentcdodds** [comment]
Nice!!
