### ISSUE TITLE
Allow hiding things from the the submission

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#239]
When the user submits a password, I don't want that coming back in the HTTP response.

Right now this is what I'm doing:

```ts
	const formData = await request.formData()
	const submission = parse(formData, {
		schema: LoginFormSchema,
		acceptMultipleErrors: () => true,
	})
	// get the password off the payload that's sent back
	delete submission.payload.password
	// @ts-expect-error - conform should probably have support for doing this
	delete submission.value?.password
```

I think we could use the new `report` API to handle this:

```ts
report(submission, { hideFields: ['password'] })
```

Thoughts?

**Comment by edmundhung** [comment]
I have a few concerns here:
- This option has a very limited usage. I understand that this is important for sensitive data like password or security code. Will it be better to have a more generic solution to cater for different needs in the future?
- It is easy to specify the field name if the schema is simple. But it becomes tricky with a complex structure. 
- Is the purpose only to avoid sending some data back? Will we want to have conform reset the field for you as well?

**Comment by kentcdodds** [comment]
Good questions:

1. I'm not sure what other needs this feature would serve in the future
2. That's fair. I'm not sure how to address that.
3. This is only to avoid having the password in the HTML or json that's sent back. No need to reset what's already in the DOM.

**Comment by edmundhung** [comment]
This is now supported with `submission.reply({ hideFields: ['password'] })`.
