### ISSUE TITLE
Support Valibot

### ISSUE THREAD

**Issue by gustavopch** [edmundhung/conform#240]
Valibot ([repo](https://github.com/fabian-hiller/valibot), [announcement](https://www.builder.io/blog/introducing-valibot)) is a new validation library that seeks to provide a similar experience to Zod, but in a tree-shakeable way. From their annoucement:

> For example, to validate a simple login form, Zod requires [11.51 KB](https://bundlejs.com/?q=zod&treeshake=%5B%7B+object%2Cstring+%7D%5D) whereas Valibot requires only [0.7 KB](https://bundlejs.com/?q=valibot&treeshake=%5B%7B+email%2CminLength%2Cobject%2Cstring+%7D%5D).

Maybe consider adding support for it.

**Comment by edmundhung** [comment]
Hi @gustavopch,

I think it is still early to consider integrating with Valibot. As Conform is not only using the schema for validation, but also deriving constraints through an extensive schema introspection. It will require fair effort to integrate a new solution and maintain it.

But I am open to re-evaluate it in the future.

**Comment by gustavopch** [comment]
Fair enough, thanks for answering. Feel free to leave the issue open or close it if you prefer.
