### ISSUE TITLE
`import { parse } from "@conform-to/zod";` should accept `{ [k: string]: FormDataEntryValue; }` and `FormData`

### ISSUE THREAD

**Issue by jmaldon1** [edmundhung/conform#252]
Currently you can't do the following without getting a type error:

`Argument of type '{ [k: string]: FormDataEntryValue; }' is not assignable to parameter of type 'FormData | URLSearchParams'`

```tsx
const { type, ...values } = Object.fromEntries(formData);
const submission = parse(values,  // type error here
{
  schema: formSchema,
});
```

Sometimes you want to pull out data from the FormData before sending it into the schema to be parsed.

**Comment by edmundhung** [comment]
Would this works for you?

```tsx
const type = formData.get('type'); // Pick what you need from the formData
const submission = parse(values, { schema });
```

Be careful that `Object.fromEntries()` override the value of the previous entry if they share the same name, while the `parse` helper will resolves it as an array. So I won't recommend people calling `Object.fromEntries(formData)` before having it parsed by Conform.

**Comment by jmaldon1** [comment]
Yes, that can work in most cases.

So `formData.get("type")` will not remove `type` from the formData. What happens if you want to remove certain fields from the formData before passing it into `parse`?

**Comment by edmundhung** [comment]
You can delete it with `formData.delete('type')`. But I would suggest you to leave it as is because [Zod object schemas strip out unrecognized keys during parsing By default](https://zod.dev/?id=strict). Depends on how your `type` is provided, leaving it in the formData would also allow Conform to persist the data for progressive enhancement.
