### ISSUE TITLE
0.8.0 breaks the onValidate()

### ISSUE THREAD

**Issue by meza** [edmundhung/conform#259]
### Describe the bug and the expected behavior

0.8.0 breaks the onValidate functionality.
It would be nice to get some advice in the release notes or here to resolve it.

### Conform version

v0.8.0

### Steps to Reproduce the Bug or Issue

```
const [form, { email }] = useForm({
    constraint: getFieldsetConstraint(schema),
    fallbackNative: true,
    lastSubmission: lastSubmission,
    onValidate: function ({ formData }) {
      return parse(formData, { schema: schema });
    },
    shouldRevalidate: 'onInput',
    shouldValidate: 'onInput'
  });
```

This now results in this:

```
src/components/molecules/NewsletterForm/index.tsx(78,5): error TS2322: Type '({ formData }: { form: HTMLFormElement; formData: FormData; }) => Submission<{ email: string; }>' is not assignable to type '({ form, formData, }: { form: HTMLFormElement; formData: FormData; }) => Submission | Submission<{ email: string; }>'.
  Type 'Submission<{ email: string; }>' is not assignable to type 'Submission | Submission<{ email: string; }>'.
    Type 'import("./node_modules/@conform-to/dom/parse").Submission<{ email: string; }>' is not assignable to type 'import("./node_modules/@conform-to/react/node_modules/@conform-to/dom/parse").Submission<{ email: string; }>'.
      Types of property 'error' are incompatible.
        Type 'Record<string, string | string[]>' is not assignable to type 'Record<string, string[]>'.
```

### What browsers are you seeing the problem on?

Others

**Comment by edmundhung** [comment]
Hi @meza, can you confirm if you have updated all the conform packages to **v0.8.0**? It looks like it is still using an older version on one of the packages.

**Comment by meza** [comment]
I'll check in a second. This all comes back to the very annoying breaking changes in minor patches as my dependabot keeps on thinking that things are safe to update 😅 
I'll get back to you in a moment

**Comment by meza** [comment]
So seems like that error is now gone by making sure everything is updated. However, I'm now getting this 
<img width="531" alt="image" src="https://github.com/edmundhung/conform/assets/211977/66c2fdde-bc4c-47ec-8d40-d0c3a3fc58cc">

It doesn't seem to be returning the errors I've given Zod.

```typescript
import { z } from 'zod';

export const addTeamMemberSchema = z.object({
  assessmentId: z.string(),
  email: z.string().min(1, 'validation.email.required').email('validation.email.invalid'),
  role: z.string().min(1, 'validation.role.required')
});
```

**Comment by meza** [comment]
Same on the UI in the browser, it's not using the custom error message

**Comment by edmundhung** [comment]
It is the expected behaviour as conform now adhere to zod's behaviour. You will need to set the required error instead. Please take a look of the release note.

**Comment by edmundhung** [comment]
FYI, I don't think there will be any more breaking changes until v1 as we are heading to v1 next. Feel free to reopen the issues if you have a hard time upgrading :)
