### ISSUE TITLE
optional schema fields not working in Node 18 due to `File is not defined` error

### ISSUE THREAD

**Issue by jessethomson** [edmundhung/conform#279]
### Describe the bug and the expected behavior

Using the `parse` function from `@conform-to/zod` produces a `ReferenceError: File is not defined` error when passed a zod schema with an optional field and run using Node 18.

However, everything works fine:
1. when using Node 18 but _without_ having the field be optional
2. when the code is run in the browser, including the optional field
3. when using Node 20 (because Node 20 implements the `File` class), including the optional field

**Expected behavior:**

The following code should run in NodeJS 18 without any errors
```
import { parse } from '@conform-to/zod';
import { z } from 'zod';

parse(new FormData(), { schema: z.string().optional() });
```

**Actual Behavior:**

Running the code above in NodeJS 18 breaks with the error `ReferenceError: File is not defined`, and references the following line of code: 

https://github.com/edmundhung/conform/blob/main/packages/conform-zod/coercion.ts#L58

### Conform version

0.8.0

### Steps to Reproduce the Bug or Issue

Put the following code in a `repro.mjs` file and then run `node ./repro.js` using Node 18.
```
import { parse } from '@conform-to/zod';
import { z } from 'zod';

parse(new FormData(), { schema: z.string().optional() });
```

**Comment by edmundhung** [comment]
Thanks for reporting the issue @jessethomson. This should be fixed on [v0.8.1](https://github.com/edmundhung/conform/releases/tag/v0.8.1).
