### ISSUE TITLE
Error from lastSubmission no displayed when field is using useInputEvent

### ISSUE THREAD

**Issue by stephen776** [edmundhung/conform#302]
### Describe the bug and the expected behavior

I have a form with several normal text inputs and a datepicker input (Let's call it `myDateField`) that's been implemented per the docs using `useInputEvent`

All validation and error message display works fine with client side validation.

The issue arises when I return lastSubmission from my `action` and it contains errors.

All field level errors for my normal text fields display just fine, however if my submission includes a single validation error for `myDateField` the error is not displayed at all. Logging the values for that particular `field` shows an empty `error` array.

Here's where it's more strange... if my `lastSubmission` ALSO includes a validation error for one of the text inputs, ALL error now display correctly. (including the error for `myDateField`)

### Conform version

v.0.9.0

### Steps to Reproduce the Bug or Issue

1. Have a form with normal text inputs and a field implemented with `useInput` event
2. Return a validation error for the `useInput` event field in the `lastSubmission`
3. Error will not display.

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by stephen776** [comment]
Here are some screenshots of my actual `lastSubmisson` json:

This does not work. No error displayed. Nothing in `error` array at field level
![image](https://github.com/edmundhung/conform/assets/565167/5d1d3389-7f31-4925-8e34-e328f6f4b0b3)


// This works. All error display at field level properly
![image](https://github.com/edmundhung/conform/assets/565167/2f83b06f-d89f-4dc5-afb0-ca84370a437b)

**Comment by edmundhung** [comment]
> All field level errors for my normal text fields display just fine, however if my submission includes a single validation error for myDateField the error is not displayed at all. Logging the values for that particular field shows an empty error array.

> Here's where it's more strange... if my lastSubmission ALSO includes a validation error for one of the text inputs, ALL error now display correctly. (including the error for myDateField)

I suspect you might have run into a zod bug with related to `z.preprocess()` like [this one](https://github.com/colinhacks/zod/issues/2687). If you are running with zod v3.22, please check if downgrading to v3.21 fix the issue.

**Comment by edmundhung** [comment]
Feel free to reopen if downgrading to v3.21 does not work for you :)
