### ISSUE TITLE
Conditionally rendered fields break onInput revalidation

### ISSUE THREAD

**Issue by halljus** [edmundhung/conform#306]
### Describe the bug and the expected behavior

Conditionally rendered Conform fields seem to lose their onInput revalidation once the condition changes. For example, for two (mutually exclusive) conditionally rendered inputs A and B:

1. Render InputA
2. Submit (firing the first validation)
3. Render InputB instead of InputA
4. Render InputA instead of InputB
5. InputA's onInput revalidation is now broken (you can submit again to fix it)

### Conform version

v0.9.0

### Steps to Reproduce the Bug or Issue

https://stackblitz.com/edit/remix-run-remix-dtzhfe?file=app%2Froutes%2F_index.tsx

Instructions are baked into the reproduction.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Additional context

Note: our real schema is more complicated than this, with nested conditional fields, so things like discriminated unions didn't work as Zod doesn't support nested DUs, etc. so this `superRefine` approach was what worked best for us. But I doubt the schema format has anything to do with this anyway. To solve the revalidation problem, we had to hide/show fields via the `hidden` attribute rather than conditionally rendering them. It's a workaround, but probably not very idiomatic with regards to React, so we'd prefer to be able to conditionally render them instead if possible.

**Comment by edmundhung** [comment]
If I understand correctly, you are expecting input A to be revalidated when you switch the type back.

The behaviour here is indeed working as per the current design. As the input has been unmounted whenever the type is changed, it is considered a new input that are never validated and follows `shouldValidate` option (which defaults to `onSubmit` in your example). This design is mainly inspired by how field list is handled. (i.e. If an item is deleted and then re-inserted, it will be considered a new item so it won't be revalidated right away). 

Does this design make sense to you? I find this question interesting as I am working on something that actually have the behaviour you want accidentally and I am now wondering what should be the correct behaviour, or at least the default behaviour here.

**Comment by halljus** [comment]
Thanks, your explanation makes sense. It sounds like we'll just have to choose between the available behaviors based on the combination of conditional rendering + `shouldValidate` + `shouldRevalidate`.

One confusing thing is that the validation error for InputA is still there, even though it's a "new" input after unrendering/rendering it. Is _that_ intended behavior? If so, is there a way to clear the error when reintroducing InputA? If the worst case was the newly rerendered InputA started fresh (no errors, no validation until submit), we might be able to live with that (even though it's not quite the UX we were going for). But because the error is still there (in fields.inputA.errors from useForm), we can't really consider this as an option.

As for whatever you're working on and future behavior, it's hard to say what is more "correct". My colleague and I expected that because we had attempted to submit (thus triggering validation, due to the default value of `shouldValidate: 'onSubmit'`), all fields (currently shown or not) would start participating in onInput validation (due to our setting of `shouldRevalidate: 'onInput'`), but we also understand from a technical level, the dynamically shown inputs are "new". In the case of a list, we would have also expected a newly added item to the list would have onInput validation in our scenario, but it wouldn't be validated until input had changed, so it would appear valid until they typed in it or something, right? That seems fine. If it started out invalid, that would be bad, but that doesn't sound like that would be the case. I don't know, complex forms are annoying. :P

**Comment by edmundhung** [comment]
> One confusing thing is that the validation error for InputA is still there, even though it's a "new" input after unrendering/rendering it. 

That sounds like a bug which I believe is a limitation of the current implementation.

For now, I will suggest you to keep using the hidden attributes trick to keep them mounted or trigger a validation on the field manually. You can achieve it using the requestIntent helper with the validate intent.

There will be a new architecture  with the behaviour you wanted. It will probably be the default behaviour but I will need to figure out a way to override it as well. Hopefully you will find an alpha version out before November :)

**Comment by edmundhung** [comment]
You can now expect the exact behaviour with v1.0.0.

**Comment by halljus** [comment]
> You can now expect the exact behaviour with v1.0.0.

Sweet, can't wait to upgrade and try it out! Thanks for all your hard work.

**Comment by halljus** [comment]
> You can now expect the exact behaviour with v1.0.0.

So, this _almost_ works in v1.0.1... conditionally rendering native inputs works great, but conditionally rendering a hidden input used for receiving events and forwarding to a custom non-native input (e.g., focus from Conform when it's the first invalid input) blows up.

I haven't been able to identify why/how it blows up exactly, but it has something to do with the controlled value (from `useInputControl`) changing on its own as soon as the condition to render the hidden input becomes true and the hidden input gets rendered.

Any idea what's going on here? I can try to make another reproduction if needed, but you always seem to already know what the problem is so I'll wait this time. 😅

**Comment by edmundhung** [comment]
A repo would be great for this case. 

How are you conditionally rendering the custom input? I can think of an issue with the hidden input messed up if you are not unmounting the component that called `useInputControl` hooked together. As it does pollute the form data and affect validation. Is this what you are doing?

```tsx
function CustomInput() {
  const control = useInputControl();

  // ...
}

function Example() {
  const [state, setState] = useState()

  return (
    <diV>
       {state === 'abc' ? <CustomInput /> : null}
    </div>
  );


}

```

**Comment by halljus** [comment]
I'm not unmounting the component that calls `useInputControl` as it's the same component as the one that calls `useForm`. Currently doing this:

```tsx
function Example() {
  const [form, fields] = useForm({ ... });
  const control = useInputControl({ ... });
  const [cond, setCond] = useState(false);
  const customNonNativeInputRef = useRef(null);

  return (
    <>
      {/* field.otherThing radio input that toggles cond */}

      {cond ? (
        <>
          <CustomNonNativeInput ref={customNonNativeInputRef} />
          <input
            name={fields.thing}
            defaultValue={fields.thing.initialValue}
            className="visually-hidden"
            tabIndex={-1}
            onFocus={() => {
              customNonNativeInputRef.current?.focus();
            }}
          />
        </>
      ) : null}
    </>
  );
}
```

I'll throw a repro together tomorrow if you don't stop me before then. 🙂

**Comment by edmundhung** [comment]
I think the issue is clear to me now. So a repo is not needed. Thanks and sorry for the trouble so far.

So what's going wrong? The `useInputControl()` hook thought there is no input rendered for `fields.thing` at first (assume your condition is false initially) and inserted an hidden input for you. Then, when you select the radio button and render the custom input with the hidden input, the DOM has two input for the same fields and the formdata is polluted with it.

We can introduce an option to the `useInputControl()` for this behaviour. But I start to believe that the idea of having `useInputControl()` inserting a hidden input for you isn't a reliable solution 🙃 I am very likely looking into introducing a new hook that does what `useInputControl()` does except this particular behaviour and deprecate it.

**Comment by halljus** [comment]
Yep, that matches what I'm seeing exactly so I think you've got it. I'll render them unconditionally for now and await the new `useControl` hook (or whatever you call it). 👍 Thanks, Edmund!
