### ISSUE TITLE
Installation instructions should mention `@conform-to/dom`

### ISSUE THREAD

**Issue by lensbart** [edmundhung/conform#310]
### Describe the bug and the expected behavior

Since `@conform-to/dom` is requested by `@conform-to/zod`, it must be installed as well. (Yarn 2+ is a bit stricter regarding such dependency requirements, and will exit with an error code upon importing a dependency which is not listed in `dependencies` in `package.json`.)

### Conform version

v0.9.0

### Steps to Reproduce the Bug or Issue

Try installing `@conform-to/zod` with Yarn 2+ (here 4.0.0-rc.52)

**Comment by edmundhung** [comment]
Thanks for the report. Are you installing the zod resolver alone or with the react adapter? (i.e. `@conform-to/react`). The dom package is an internal dependency of it so I was hoping it get resolved correctly with the peer dependency listed on zod. But if it doesn't work out, I will take a deeper look.

**Comment by lensbart** [comment]
I tried it either way. The problem is due to some validation done by Yarn, which is on a per-package basis (and so isn’t affected by the actual presence of `@conform-to/dom`, or `@conform-to/react` for that matter).

**Comment by quantuminformation** [comment]
I think installation instructions should be added. Do I need to install is `conform-to` etc etc?

**Comment by edmundhung** [comment]
`@conform-to/zod` now marks `@conform-to/dom` as a direct dependency instead of a peerDependency.
