### ISSUE TITLE
Missing documentation for description(Id) and attributes

### ISSUE THREAD

**Issue by luzat** [edmundhung/conform#313]
### Describe the bug and the expected behavior

Descriptions (`description: true`, `descriptionId`, `aria-describedby`) and their interaction with errors as introduced in #120 do not seem to be documented. I would like to find the type of a field, including the property `descriptionId`, explained in the [parse](https://conform.guide/api/zod#parse) documentation.

A list of attributes generated by `conform.input` would be nice, too. I had to look into the source code to see whether `required`, `autoFocus` and others would be generated.

### Conform version

v0.9.0

### Steps to Reproduce the Bug or Issue

1. Try to find documentation for `descriptionId` in the repository or on [conform.guide](https://conform.guide/).
2. Fail.

**Comment by adaboese** [comment]
How do I make input not required?

**Comment by edmundhung** [comment]
This should be documented now with the `description` option renamed to `ariaDescribedBy`
