### ISSUE TITLE
Radix UI specific inputs

### ISSUE THREAD

**Issue by jansedlon** [edmundhung/conform#315]
### Describe the bug and the expected behavior

Hi! Radix UI is using a lot of custom logic for handling all kinds of different inputs. For example the issue I'm facing is with component `RadioGroup`. 

If I'm using `RadioGroup`, bind conform to it and change a value, it goes to a function in conform called `isFormControl`. It returns false, because the element is `div`. However it has property `role` set to `radiogroup`. 

Do you think it could be extended in some way to handle these kinds of inputs? I think semantically, `role` property should have its weight, not only `tagName`.

### Conform version

v0.9.0

### Steps to Reproduce the Bug or Issue

1. Install conform with Radix `@radix-ui/react-radio-group` 
2. Create form with Conform

```tsx
const RadioGroup = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root> & {
    label?: string;
    optional?: boolean;
    error?: string;
  }
>(({ className, label, error, optional, ...props }, ref) => {
  const { t } = useTranslation("ui");
  return (
    <div className="flex flex-col gap-y-2">
      {label && (
        <Label className={cn("flex items-center", error && "text-destructive")}>
          {label}
          {optional && (
            <span className="text-xs text-muted-foreground">
              &nbsp;({t("optional")})
            </span>
          )}
        </Label>
      )}
      <RadioGroupPrimitive.Root
        className={cn("grid gap-2", className)}
        {...props}
        ref={ref}
      />
      {error && (
        <span className="self-start text-xs font-medium text-destructive">
          {error}
        </span>
      )}
    </div>
  );
});
RadioGroup.displayName = "RadioGroup";

const RadioGroupItem = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Item> & {
    label?: string;
  }
>(({ className, children, label, ...props }, ref) => {
  const inputId = React.useId();
  const labelId = React.useId();

  return (
    <div className={cn("flex items-center space-x-2", className)}>
      <RadioGroupPrimitive.Item
        ref={ref}
        aria-labelledby={label ? labelId : undefined}
        className="aspect-square h-4 w-4 rounded-full border border-primary text-primary ring-offset-background focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
        {...props}
        id={props.id ?? inputId}
      >
        <RadioGroupPrimitive.Indicator className="flex items-center justify-center">
          <Circle className="h-2.5 w-2.5 fill-current text-current" />
        </RadioGroupPrimitive.Indicator>
      </RadioGroupPrimitive.Item>
      {label && (
        <Label
          className={cn(
            "text-sm font-medium leading-4",
            props.disabled && "cursor-not-allowed opacity-70",
          )}
          htmlFor={props.id ?? inputId}
          id={labelId}
        >
          {label}
        </Label>
      )}
    </div>
  );
});
RadioGroupItem.displayName = "RadioGroupItem";

{/* And then render it like */}
<RadioGroup
                  className="mt-4 flex gap-4"
                  error={fields.layout.error}
                  ref={layoutRef}
                  {...conform.input(fields.layout)}
                  onValueChange={(v) => {
                    layoutInputEvent.change(v);
                    setSelectedLayout(v as SchemaData["layout"]);
                  }}
                >
                {/* Content */}
                </RadioGroup>
```

### What browsers are you seeing the problem on?

Chrome

**Comment by edmundhung** [comment]
> Do you think it could be extended in some way to handle these kinds of inputs? I think semantically, role property should have its weight, not only tagName.

I am no expect on accessibility roles. Is it associated with an input through some sort of ids? If yes, i am happy to extends it. All Conform needed is the name of the input and a reference to the corresponding form element or form id.

> If I'm using RadioGroup, bind conform to it and change a value, it goes to a function in conform called isFormControl. It returns false, because the element is div.

It seems like the Radix team prefer not to expose the form control element as it does on the [Checkbox](https://github.com/radix-ui/primitives/discussions/874) component. There are 2 solutions:

1. Do not rely on the hidden input created by Radix. (i.e. Don't set a name to the Radix component and make your own hidden input that you can access)

2. Try to access the element using a different approach like [this one](https://github.com/epicweb-dev/epic-stack/blob/main/app/components/forms.tsx#L105-L111), e.g. `document.getElementById(..)` or `form.elements.namedItem(inputName)?.[0]` (Note: the extra `?.[0]` is needed in case there is multiple elements with the same name)

**Comment by leonardo-ornelas** [comment]
I had a similar issue since I am using a Switch Radix component. When you use it inside a form the Radix renders a button alongside an input.

I couldn't use `?[0]` , because I am using a similar implementation that @edmundhung [mentioned](https://github.com/epicweb-dev/epic-stack/blob/main/app/components/forms.tsx#L105-L111)
and for my page, is a list of many Switchs.

I resolve this issue using:
`buttonRef.current?.nextElementSibling`

Now, the ref is pointing to this closest radix input, therefore all conform's `control...` should point to the correct element input.
