### ISSUE TITLE
`getFieldsetConstraint` does not parse attributes correctly 

### ISSUE THREAD

**Issue by diurivj** [edmundhung/conform#316]
### Describe the bug and the expected behavior

Consider the following schema:

```ts
export const InsertUserSchema = z.object({
	email: z.string().email(),
	name: z.string().min(2),
	password: z.string().min(8)
});
```

When trying to use `getFieldsetConstraint` method, I get a warning error:
`Warning: Extra attributes from the server: required,minlength`

This happens only when I add the `min` constraints to the zod schema 

### Conform version

0.9.0

### Steps to Reproduce the Bug or Issue

1. Using remix
2. Use this schema
```ts
export const InsertUserSchema = z.object({
	email: z.string().email(),
	name: z.string().min(2),
	password: z.string().min(8)
});
```

3. Action code
```tsx
export async function action({ request }: DataFunctionArgs) {
	const formData = await request.formData();
	const submission = await parse(formData, {
		schema: InsertUserSchema.superRefine(async (data, ctx) => {
			const existingUserId = await checkIfUserExists(data.email);

			if (existingUserId) {
				ctx.addIssue({
					path: ['email'],
					code: z.ZodIssueCode.custom,
					message: 'A user already exists with this email'
				});
				return;
			}
		}),
		async: true
	});

	if (submission.intent !== 'submit') {
		return json({ status: 'idle', submission } as const);
	}

	if (!submission.value) {
		return json({ status: 'error', submission } as const, { status: 400 });
	}

	const { password, ...user } = submission.value;
	const userId = await createUser(user, password);

	return createUserSession({
		request,
		redirectTo: '/',
		remember: true,
		userId
	});
}
```

4. Route component
```tsx
	const actionData = useActionData<typeof action>();

	const id = useId();
	const [form, fields] = useForm({
		id,
		constraint: getFieldsetConstraint(InsertUserSchema),
		lastSubmission: actionData?.submission,
		onValidate({ formData }) {
			return parse(formData, { schema: InsertUserSchema });
		},
		shouldValidate: 'onBlur'
	});

        .... 
```

### What browsers are you seeing the problem on?

Chrome, Others

### Screenshots or Videos

<img width="718" alt="Screenshot 2023-10-26 at 12 25 21" src="https://github.com/edmundhung/conform/assets/37969385/ffad7ad3-fc7a-4b7d-84c6-930cd457d93e">

**Comment by edmundhung** [comment]
I have seen this happened before because of CJS/ESM issue, in which your app has two copy of zod on the client and conform failed to introspect the schema on the client side. Can you try copying your changes into a clean remix/epic stack project and see if the same thing happens?

**Comment by diurivj** [comment]
Ok, nvm. 
I found what the issue was, I was using a zod schema coming from a `.server.ts` file, that was the big issue, really hard to spot because I just forgot the context of a .server file
