### ISSUE TITLE
useFieldList does not reupdate

### ISSUE THREAD

**Issue by jamalsoueidan** [edmundhung/conform#327]
### Describe the bug and the expected behavior

useFieldList is broken when rendering inside outlet

orders.tsx
```js
<Button to="orders/1">order 1</Button>
<Button to="orders/2">order 2</Button>
<Outlet />
```

orders.$id.tsx
```js
export default function OrderId() {
  const defaultValue = useLoaderData<typeof loader>();
  const lastSubmission = useActionData<typeof action>();

  const [form, fields] = useForm({
    lastSubmission,
    defaultValue,
    onValidate({formData}) {
      return parse(formData, {
        schema,
      });
    },
    fallbackNative: true,
    shouldValidate: 'onSubmit',
    shouldRevalidate: 'onInput',
  });

  const slotsList = useFieldList(form.ref, fields.slots);
}
```

fields.slot getting updated with new values from defaultValue, but slotsList is not, it actually make the app slow!

```
{
 orders: [{id: 1, test: 'a'}]
}

{
 orders: [{id: 2, test: 'b'}]
}
```
### Conform version

latest version

### Steps to Reproduce the Bug or Issue

See previous comment.

**Comment by jamalsoueidan** [comment]
I hope it make sense!

**Comment by jamalsoueidan** [comment]
I fixed the problem by giving the outlet a key, then react will re-create the whole page.

**Comment by aerojeyenth** [comment]
@jamalsoueidan I am facing a similar problem but I don't think setting a key for the outlet is a right approach do not this operation be very heavy ? I request this issue to be re-opened.

**Comment by jamalsoueidan** [comment]
> @jamalsoueidan I am facing a similar problem but I don't think setting a key for the outlet is a right approach do not this operation be very heavy ? I request this issue to be re-opened. 

Maybe you create new bug and link to this bug.
