### ISSUE TITLE
Allow keeping reference to removed inputs

### ISSUE THREAD

**Issue by Frantss** [edmundhung/conform#330]
### Describe the bug and the expected behavior

Hi! I'm trying to create a filter component that consists of a popover (using radix [popover](https://www.radix-ui.com/primitives/docs/components/popover) component) with a bunch of checkboxes inside it's content (using [conform.collection](https://conform.guide/checkbox-and-radio-group#checkbox)). 

I'm facing the following issues, once the popover is closed the `input` elements are removed from the dom, so conform looses any reference to these fields.

I was thinking maybe conform would provide an API to keep the reference to removed inputs, something similiar to felte's does with [data-felte-keep-on-remove](https://felte.dev/docs/react/dynamic-forms).

### Conform version

0.9.1

### Steps to Reproduce the Bug or Issue

```jsx
const [form, { filters }] = useForm(...);

<Popover>
      <PopoverTrigger>Add filter</PopoverTrigger>
      <PopoverContent>
        {conform
              .collection(filters, {
                type: 'checkbox',
                options,
              })
              .map(props => (
                <input {...props} />
              )
         }
       </PopoverContent>
</Popover>
```

### What browsers are you seeing the problem on?

Chrome

**Comment by edmundhung** [comment]
Hi @Frantss, Conform does not keep any reference of an input and relies on the FormData API to construct the data based on the DOM. Please check if radix have an option to avoid unmounting the content or you can render hidden inputs with the value selected whenever the popover is closed.

**Comment by edmundhung** [comment]
Feel free to reopen this if you have any other questions :)
