### ISSUE TITLE
Whitespace chars in number fields are incorrectly coerced to 0 with zod

### ISSUE THREAD

**Issue by marcomuser** [edmundhung/conform#333]
### Describe the bug and the expected behavior

When using z.number() with @conform-to/zod, whitespace characters, e.g. `" "` are incorrectly coerced to 0 by the enableTypeCoercion fn. The problem is that the JS `Number` function handles whitespace characters as 0. A fix would be to use `parseFloat` instead of `Number` on [L124](https://github.com/edmundhung/conform/blob/main/packages/conform-zod/coercion.ts#L124).

### Conform version

v0.9.0

### Steps to Reproduce the Bug or Issue

1. Create a number field which is validated with z.number()
2. Add whitespace characters, e.g. `"   "`
3. Validation passes and the input value is coerced to `0`. Validation should fail instead.

**Comment by edmundhung** [comment]
This is now resolved in [v1.0.0](https://github.com/edmundhung/conform/releases/tag/v1.0.0).
