### ISSUE TITLE
Support submitting empty strings with Zod

### ISSUE THREAD

**Issue by davidfou** [edmundhung/conform#361]
### Describe the bug and the expected behavior

Well done for the lib, the documentation is crystal clear and I had no issue setting it up :clap:

The lib doesn't allow a user to send an empty string when validating with `zod`.  That's an issue for us.

Here is the investigation I've done:

On the line [`packages/conform-zod/parse.ts#L81`](edmundhung/conform/blob/main/packages/conform-zod/parse.ts#L81), when replacing `schema` by `config.schema`, the errors are gone. The schema is modified at [`packages/conform-zod/parse.ts#L47-L51`](edmundhung/conform/blob/main/packages/conform-zod/parse.ts#L47-L51). In our case, removing the lines [`packages/conform-zod/coercion.ts#L42-L44`](https://github.com/edmundhung/conform/blob/main/packages/conform-zod/coercion.ts#L42-L44) is more appropriate.

Did I miss something to support an empty string?

### Conform version

v0.9.1

### Steps to Reproduce the Bug or Issue

The following code highlights the issue:

```js
const {z} = require("zod")
require('@conform-to/dom')
const { parse } = require('@conform-to/zod');

 const schema = z.object({
  email: z.string({ required_error: 'Email is required' }),
  password: z.string({ required_error: 'Password is required' }),
});

console.log(schema.safeParse({email: "", password: ""}))

const formData = new FormData();
formData.append("email", "");
formData.append("password", "");
console.log(parse(formData, { schema }))
```

The native Zod schema is fine with the payload, Conform reports `email` and `password` are required.

The code can be executed at: https://runkit.com/embed/oworgm1spt0h

**Comment by davidfou** [comment]
Thanks for your quick response :+1: 

I tried that alternative already, and it works.

The same schema is used at other places of the application. So, it means marking the field optional will make other parts weaker. That's why we needed a different approach, and there is room to adapt conform slightly for that case.

I only partially follow you on your explanation. With Zod, a way to force non-empty strings would be to add `.min(1)`. That's why I found replacing empty strings with undefined counterintuitive.

**Comment by edmundhung** [comment]
The native required check from zod and min(1) behaves a bit different actually.

Consider a required email field:
`z.string().min(1, "required").email("invalid email")`

If you pass an empty string, zod returns you two errors: required and invalid email

With conform, you defined it as `z.string().email("invalid email")`

If you pass an empty string, you get only one error: required

It might be subjective which one is better here. But let's consider the case with optional field as well:

It might be tempting to just remove the min check:

`z.string().email("invalid email")`

However, this won't work. If you pass an empty string, zod will tell you the email is invalid.

To solve this, you will have to strip the empty string in a preprocess and mark the schema as optional which is exactly what conform is doing for you.

**Comment by davidfou** [comment]
I see your point. If we don't reuse the same schema at other places (where we want to ensure a program to return all the properties), I would be okay with your approach of adding the optional. However, our case is edgy, and what you explained might cover better how people will use the library you developed.

Other people might fall into the same trap. e.g. `having z.string().optional().default("")`. When using that schema with conform, the coercion removes the `.default("")`.

But as mentioned earlier, we might be talking about edge cases, and it's understandable the library prioritizes the most common cases.

Thanks a lot for your support.
