### ISSUE TITLE
fallback lsp range format with several buffers get messed

### ISSUE THREAD

**Issue by rtgiskard** [edmundhung/conform#369]
### Describe the bug and the expected behavior

fallback lsp range format modifies the wrong buffer

### Conform version

v5.1, commit: ad2b5ec

#### Provide two files:

`a.cc`:  maybe valid cpp source is enough, formatted or not
```

#define A_CC

#include <iostream>
using namespace std;

int main() { cout << "Hello World!"; }
```

`b.cc`: lsp format will change the content
```
#define B_CC

#include <iostream>
using namespace std;



int main() {
  cout << "Hello World!";
  return 0;
}   
```

#### Configuration: 

1. `clangd` lsp setup for `cpp`
2. conform format with fallback to lsp for the filetype: cpp

#### Steps to reproduce:

1. `nvim a.cc`
2. apply conform format (run at least once)
3. load `b.cc` with `:e b.cc` in nvim
4. apply conform format (this will trigger the bug)

#### bug behavior base on the above operation:

For the conform format operation on `b.cc`:
the first one may finish success, the latter format will raise Error without running the format callback:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:501: Invalid 'start_col': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_text'
	/usr/share/nvim/runtime/lua/vim/lsp/util.lua:501: in function 'apply_text_edits'
	.../share/nvim/lazy/conform.nvim/lua/conform/lsp_format.lua:24: in function 'apply_text_edits'
	.../share/nvim/lazy/conform.nvim/lua/conform/lsp_format.lua:103: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Additional context

You may use the [`lazyNvim: dev`](https://github.com/rtgiskard/lazyNvim/tree/dev)  branch to apply the test, use key shot <C-f> for conform format operation. the `format()` wrapper is located in `init/utils.lua:format()`.

**Comment by edmundhung** [comment]
I guess you are looking for [conform.nvim](https://github.com/stevearc/conform.nvim). This is the repository of a web form validation library :)

**Comment by rtgiskard** [comment]
😂ome bit of embarrassing🙈 thanks for your reminder😂
