### ISSUE TITLE
QUESTION: How to deal with two forms on one page

### ISSUE THREAD

**Issue by johnsonthedev** [edmundhung/conform#37]
Hi Edmund, 

Have you thought about how to handle two forms on one page with this library? 

If you have an example it would be super helpful.

Thanks

**Comment by edmundhung** [comment]
Hi @johnsonthedev,

I guess your question is about how to handle different schemas in the same `ActionFunction` with Remix. If yes, then one solution would be utilizing hidden input to help you identify which form is submitted. 

I hope this [example]https://codesandbox.io/s/sad-morning-1wdsmc?file=/app/routes/index.tsx) answer you question.

**Comment by johnsonthedev** [comment]
Perfect thank you so much for the example. This was super helpful!

**Comment by sockthedev** [comment]
If anyone has a more update to date example, that is also all-in on TypeScript, I'd love to see it.

**Comment by edmundhung** [comment]
Hi @sockthedev. Here is an updated [example](https://codesandbox.io/s/conform-multiple-form-s8w8r2) that showcase 2 approaches. One using action with a custom search, the other uses a hidden input. (Note: There is nothing specific to Conform here)

**Comment by sockthedev** [comment]
Thanks @edmundhung! That was a really helpful example. I was going off course by trying to utilise the intent within conform submission to distinguish between form schemas, which was not feeling natural at all. Your higher level discriminator (`?form=foo`) made it click for me now.
