### ISSUE TITLE
Empty strings coerced as undefined instead of null or ''

### ISSUE THREAD

**Issue by kenn** [edmundhung/conform#395]
### Describe the bug and the expected behavior

Right now, there's no way to delete a string field (Prisma + Postgres) — once you enter something into a nullable field, there's no way to make it empty again.

This is because conform-zod coerce `''` into `undefined` and Prisma treats `undefined` as if the field is non-existent in SQL.

Prisma is pretty clear about the difference between `null` vs `undefined`:
https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/null-and-undefined

Relevant conform-zod code here:
https://github.com/edmundhung/conform/blob/main/packages/conform-zod/coercion.ts#L42-L44

Right now, `submission.value` after parse looks like this:

```js
{
  name: undefined,
  address: {
    street: undefined,
    state: undefined,
    zip: undefined,
  }
}
```

So when you pass it to DB to update the record:

```js
await prisma.user.update({
  where: { id },
  data: { ...submission.value }
})
```

It does nothing because it's treated as if all keys are missing and just passing `{ address: {} }`.

We need an option to stop this behavior and coerce as `null` or `''` to restore the difference in semantics between those falsy values.

To be more precise, [SQL databases have different behaviors around empty strings vs NULL](https://www.migops.com/blog/null-and-empty-string-in-oracle-vs-postgresql-vs-sql-server/). So some might even want to handle `''` and `null` differently (no coercion at all), but I digress.

### Conform version

v0.9.1

### Steps to Reproduce the Bug or Issue

Here's the server-side code to reproduce this problem:

```js
import { parse } from '@conform-to/zod'

export async function action({ request }) {
  const formData = await request.formData()
  const submission = parse(formData, { schema })

  await prisma.user.update({
    where: { id },
    data: { ...submission.value }
  })
}
```

### What browsers are you seeing the problem on?

Chrome

**Comment by edmundhung** [comment]
You should be able to default it to `null` as mentioned [here](https://github.com/edmundhung/conform/discussions/387#discussioncomment-8249412)

```tsx
const schema = z.string().nullable().default(null)
```

The reason why we strip empty string to `undefined` is exactly to support optional field properly as Zod treat empty string just like any other string and will continue processing all the validation even though we don't expect. Imagine an email schema like this:

```ts
const schema = z.string().email().optional()
```

If we pass an empty string to this schema, Zod will fail it with a validation error about invalid email. The only way is to pass an `undefined` and zod will skip the email validation and gives a success result.

**Comment by kenn** [comment]
Ohh that's good to know, thanks @edmundhung !
