### ISSUE TITLE
Compatibility issue with `ZodCatch`

### ISSUE THREAD

**Issue by aaronadamsCA** [edmundhung/conform#397]
### Describe the bug and the expected behavior

If I add a `.catch()` to a `z.number()` schema, `parseWithZod()` always returns the catch value, even with a valid input that matches the Zod schema.

### Conform version

v1.0.0-rc.1

### Steps to Reproduce the Bug or Issue

Minimal reproduction: https://stackblitz.com/edit/remix-run-remix-qxwt5m?file=app%2Froutes%2F_index.tsx

Expected behaviour:

```ts
const schema = z.object({
  page: z.number().int().min(1).safe().catch(1),
});

expect(
  parseWithZod(new URLSearchParams('page=2'), {
    schema,
  })
).toEqual({
  status: 'success',
  payload: {
    page: '2',
  },
  value: {
    page: 2,
  },
  reply: expect.any(Function),
});
```

Actual behaviour: `value` is always equal to `{ page: 1 }`.

### Additional context

The use case here is validating `searchParams`, where unlike `formData` you probably just want to fall back to valid values and ignore invalid ones.

If you remove the `.catch()` from the schema, it works as expected—but of course then you can't fall back to valid values.

**Comment by edmundhung** [comment]
Looks like `safe` and `catch` is not implemented for the introspection so it is not able to inject the preprocess step to `z.number()` and fails because `"2"` is not a number 😅 Feel free to make a PR.

**Comment by edmundhung** [comment]
This is release in v1.0.0.
