### ISSUE TITLE
Typos in the new website documentation

### ISSUE THREAD

**Issue by Carlo-Piantini** [edmundhung/conform#412]
### Describe the bug and the expected behavior

There are a few typos inside of the documentation code examples found on the new Conform website, specifically where `parse` hasn't been renamed to `parseWithZod`. 

Instances I've found so far:
- Second code example in the ["Improved Validation Experience"](https://conform.guide/tutorial#improve-validation-experience) of the tutorial.
- Inside the ["Improved Submission Handling"](https://conform.guide/upgrading-v1) section of the guide of migrating to v1.

There are possibly others, so I'd do a quick copy-review of the site documentation and make sure you caught them all!

### Conform version

v.1.0.0

### Steps to Reproduce the Bug or Issue

1. Visit the [Conform website](https://conform.guide) and examine the referenced code snippets.

**Comment by narutosstudent** [comment]
im making a pr for the ones you found and a few other places

**Comment by narutosstudent** [comment]
pr here: https://github.com/edmundhung/conform/pull/415

**Comment by edmundhung** [comment]
Thanks both!
