### ISSUE TITLE
[1.0.0] Changing native value wipes out default/initial controlled value?

### ISSUE THREAD

**Issue by halljus** [edmundhung/conform#429]
### Describe the bug and the expected behavior

I'm experiencing an issue where changing the value of a native input causes the form (`form.value`) to lose the value of an unchanged controlled input (`useInputControl`). If you change the controlled input value first, it doesn't lose it. Ultimately, I noticed this because `form.dirty` was remaining true after changing the native value back to its default. Check out the reproduction. Maybe I'm just doing something wrong here?

### Conform version

v1.0.0

### Steps to Reproduce the Bug or Issue

Full reproduction here:

https://stackblitz.com/edit/remix-run-remix-dpreq3?file=app%2Froutes%2F_index.tsx

**Comment by edmundhung** [comment]
This is likely because of https://github.com/edmundhung/conform/issues/401 and should be fixed with #419. I will try to get a fix out asap.

**Comment by edmundhung** [comment]
This should resolved with [v1.0.1](https://github.com/edmundhung/conform/releases/tag/v1.0.1).

**Comment by halljus** [comment]
Confirmed, fixed in v1.0.1.
