### ISSUE TITLE
Problem removing from arrays

### ISSUE THREAD

**Issue by dusty** [edmundhung/conform#446]
### Describe the bug and the expected behavior

When removing an item from array using form.remove function, it is not removing only that item from the array. 

Relevant code

```
const schema = z.object({
  tasks: z.array(z.string()),
});

export default function Component() {
  <Form
    method="post"
    // sets all the accessiblility props
    {...getFormProps(form)}
    style={{ marginTop: "1rem" }}
  >
    <div id={form.errorId}>{form.errors}</div>

    <div style={{ paddingTop: "1rem" }}>
      {tasks.map((task, index) => {
        return (
          <div key={task.id}>
            <input {...getInputProps(task, { type: "text" })} />
            <button
              {...form.remove.getButtonProps({
                name: fields.tasks.name,
                index,
              })}
              style={{ marginLeft: "0.5rem" }}
            >
              remove
            </button>
          </div>
        );
      })}
      <button
        {...form.insert.getButtonProps({ name: fields.tasks.name })}
        style={{ marginTop: "0.5rem" }}
      >
        Add task
      </button>
    </div>

    <button style={{ marginTop: "1rem" }}>Submit</button>
  </Form>;
}
```

### Conform version

v1.0.1

### Steps to Reproduce the Bug or Issue

Open this URL: https://stackblitz.com/edit/remix-run-remix-fveq6b?file=app%2Froutes%2F_index.tsx

Add items to the array, and then click one of the buttons to remove from the array.

### What browsers are you seeing the problem on?

Chrome

### Screenshots or Videos

![2024-02-12 14 54 35](https://github.com/edmundhung/conform/assets/792/2ddf2fdf-f91f-4307-afe1-429a4191495a)

**Comment by edmundhung** [comment]
Please use `task.key` instead of `task.id` for the key.

**Comment by dusty** [comment]
Dang. Sorry I overlooked that.

Thanks so much for the help.
