### ISSUE TITLE
Form#:rf: does not exist

### ISSUE THREAD

**Issue by alindsay55661** [edmundhung/conform#461]
### Describe the bug and the expected behavior

My form in inside a Mantine Modal which does not get rendered unless it's opened. So, when `useForm` is called as the component renders, it fails to locate the form which is conditionally rendered in the modal. 

### Conform version

v1.0.0

### Steps to Reproduce the Bug or Issue

Place your form into markup that renders conditionally (like a modal). Render the component without rendering the form. Observe the error.

### What browsers are you seeing the problem on?

Chrome

### Screenshots or Videos

![image](https://github.com/edmundhung/conform/assets/270710/6d83c623-d011-44bb-947d-1596d8930f05)

**Comment by edmundhung** [comment]
We have released the `useControl` hook in [v1.0.2](https://github.com/edmundhung/conform/releases/tag/v1.0.2) which gives you more control on the form element. Feel free to share here if you still have any issue working with Modal.
