### ISSUE TITLE
File input not marked as dirty if useForm's defaultValue is defined

### ISSUE THREAD

**Issue by lucasthevenet** [edmundhung/conform#469]
### Describe the bug and the expected behavior

Hi, it's me again!  Thanks for fixing the previous file input issue, I found another bug of a similar nature.

When having a `defaultValue` configured in your `useForm` hook (for any field), the file input is not marked as dirty when a file is selected.

The expected behavior doesn't work for single nor multiple file selection.

### Conform version

v1.0.2

### Steps to Reproduce the Bug or Issue

1. Open this reproduction repo: https://stackblitz.com/edit/github-qiy4lh?file=app%2Froutes%2Fdirty-file.tsx
3. Upload any file and visualize that the dirty state does not change in comparison to when typing in the text input.

**Comment by edmundhung** [comment]
Oops! Sorry that this happened 😅 I will try to get it fixed this week.
