### ISSUE TITLE
Conform breaks Remix <Form /> submission with clientAction

### ISSUE THREAD

**Issue by QzCurious** [edmundhung/conform#473]
### Describe the bug and the expected behavior

Submitting a conform driven `<Form />` by "press Enter on input" should not make a real POST request. It should behave the same as clicking a submit button.

I've tried hard to make a very minimum reproduction to reveal root cause. I believe the bug is occurring with all of these condition:

- `clientAction` reply with `{ resetForm: true }`
  ```jsx
  export const clientAction = async ({ request }: ClientActionFunctionArgs) => {
    const formData = await request.formData();
    const submission = parseWithZod(formData, { schema });
    return submission.reply({ resetForm: true });
  };
  ```
- `useForm` with `lastResult` (of cause) AND `shouldValidate` being `"onBlur"`
  ```jsx
  const [form, fields] = useForm({
    shouldValidate: "onBlur",
    lastResult,
  });
  ```
Change the condition by one of the following workaround the bug:

- Submitting the `<Form />` by submit button works fine
- `submission.reply()`, that is, without `{ resetForm: true }`
- Use `action` instead of `clientAction` (But I want a SPA app)
- `shouldValidate` being `onInput` or `onSubmit`

### Conform version

v1.0.2

### Steps to Reproduce the Bug or Issue

1. `git clone https://github.com/QzCurious/conform-remix-vite-form-submission-bug`
2. It's a Remix Vite App
3. `pnpm i`
4. `pnpm dev` and open the web page
5. Focus on "remix form with conform" and press Enter
6. Bug happens. `<Form />` is making a real POST request instead being handled by `clientAction`

### Screenshots or Videos

https://github.com/edmundhung/conform/assets/38932402/8b952d99-9774-4349-8f23-a962df8fbb9a

### Additional context

Remix with Vite were just marked [stable](https://remix.run/blog/remix-vite-stable) today.

**Comment by edmundhung** [comment]
This is because Conform handle everything including validation as a form submission to achieve single data flow. You should either check the submission status on the client action and just return the result back similar to `action`, or if you wanna minimize it hitting the client action, just set the `onValidate` option.
