### ISSUE TITLE
Insert, remove and reorder intents do not work with button type = button

### ISSUE THREAD

**Issue by hauptrolle** [edmundhung/conform#481]
### Describe the bug and the expected behavior

When adding `type="button"` to an insert, remove or reorder intent the intent is not working anymore.

### Conform version

1.0.1

### Steps to Reproduce the Bug or Issue

1. Checkout example from website: https://conform.guide/intent-button
2. Add `type="button"` to intent buttons
3. It does nothing

**Comment by edmundhung** [comment]
All form intent are designed work before JS. Making it type button means it will not work the way it is designed. Why do you wanna restrict it?

Anyway, if you really have to do this, you can always setup a onClick handler and trigger the form intent directly:

```jsx
<button type="button" onClick={() => form.reset()} />
```
