### ISSUE TITLE
Next.js 14 error after return submission.reply()

### ISSUE THREAD

**Issue by Trimud** [edmundhung/conform#487]
### Describe the bug and the expected behavior

Hello,

I'm following Next.js integration guide with Server Actions here https://conform.guide/integration/nextjs
Everything works as expected with client side validation, but when I disable it and check if server side validation works as expected, I'm getting the following error:

> Error: Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported.

It turns out, that there's an issue when there is an input with type `file` in the form:
`<input type="file" name={fields.categoryImage.name} />`

I have managed to fix the issue by replacing `return submission.reply();` in the server action with `return JSON.parse(JSON.stringify(submission.reply()));` but this doesn't look right.

Here's my submission reply without the additional JSON.parse()

```
{
  status: 'error',
  intent: undefined,
  initialValue: {
    categoryImage: File {
      size: 0,
      type: 'application/octet-stream',
      name: 'undefined',
      lastModified: 1708791638592
    },
    categoryPublished: 'true',
    parentCategory: '0'
  },
  error: {
    categoryTitle: [ 'Required' ],
    categoryImage: [
      'Image is required',
      'Only .jpg, .jpeg, .png and .webp files are accepted'
    ]
  },
  state: {
    validated: {
      categoryPublished: true,
      categoryTitle: true,
      categoryAlias: true,
      parentCategory: true,
      categoryImage: true,
      categoryDescription: true
    }
  }
}
```

Here's my submission reply with additional JSON.parse()
```
{
  status: 'error',
  initialValue: { categoryImage: {}, categoryPublished: 'true', parentCategory: '0' },
  error: {
    categoryTitle: [ 'Required' ],
    categoryImage: [
      'Image is required',
      'Only .jpg, .jpeg, .png and .webp files are accepted'
    ]
  },
  state: {
    validated: {
      categoryPublished: true,
      categoryTitle: true,
      categoryAlias: true,
      parentCategory: true,
      categoryImage: true,
      categoryDescription: true
    }
  }
}
```

As you can see the initialValue for categoryImage is empty object.

### Conform version

v1.0.2

### Steps to Reproduce the Bug or Issue

1. Add form field of type file: <input type="file" name={fields.categoryImage.name} />
2. Add Zod validation for it, here's mine:
```
categoryImage: z.custom<File>().superRefine((file, ctx) => {
    // Check if file is submitted
    if (file?.size === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Image is required",
      });
    }
    // Check if file is not larger than allowed max file size
    if (file?.size >= MAX_FILE_SIZE) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Max file size is 4.5MB",
      });
    }
    // Check if file is not an accepted image type
    if (!ACCEPTED_IMAGE_TYPES.includes(file?.type)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Only .jpg, .jpeg, .png and .webp files are accepted",
      });
    }
  }),
```
3. Remove client side validation and use server action to submit and validate the form

### What browsers are you seeing the problem on?

Chrome

**Comment by edmundhung** [comment]
This should be fixed in [v1.0.3](https://github.com/edmundhung/conform/releases/tag/v1.0.3).
