### ISSUE TITLE
Inserting ReCaptcha 3 token in FormData before submit

### ISSUE THREAD

**Issue by shripadk** [edmundhung/conform#50]
Firstly, thank you for making this awesome form validation library. Evaluated many and finally settled on Conform as it works really well with Remix.

My question pertains to implementing ReCaptcha 3 along with a Form. I need to send a Captcha token with FormData which can be validated server-side in the `action`. The token must be generated and inserted into the FormData before the request is sent.

How should I go about doing this? Is there an obvious way to do this that I am missing? I read the documentation thoroughly but couldn't find anything that could help me in this.

Thank you!

**Comment by shripadk** [comment]
Providing relevant ReCaptcha 3 documentation for reference: [the captcha challenge is invoked programmatically](https://developers.google.com/recaptcha/docs/v3#programmatically_invoke_the_challenge).

**Comment by edmundhung** [comment]
Hi @shripadk, thanks for giving conform a try!

I will suggest you to take a look of this [article](https://sergiodxa.com/articles/add-additional-data-before-submitting-on-remix) from sergiodxa.

i.e.
```tsx
import { captcha } from '~/services/captcha.client';
import { Form, useSubmit } from '@remix-run/react';
import { useForm } from '@conform-to/react'; 

export default function Login() {
  const submit = useSubmit();
  const form = useForm({
    async onSubmit(event, { formData }) {
      // Prevent default form submission
      event.preventDefault();

      // grab the form element
      const $form = event.currentTarget;

      // Set the captcha token
      formData.set("captcha", await captcha());

      // Submit the form data and reuse the action from the form
      submit(formData, {
        method: 'post',
        action: $form.getAttribute("action") ?? $form.action,
      });
    },
  });

  return (
    <Form method="post" {...form.props}>
      <label>Email address</label>
      <input type="email" name="email" />

      <label>Password</label>
      <input type="password" name="password" />

      <button type="submit">Log In</button>
    </Form>
  );
}
```

**Comment by shripadk** [comment]
@edmundhung Thanks a lot!
