### ISSUE TITLE
flushSync was called from inside a lifecycle method

### ISSUE THREAD

**Issue by JasonColeyNZ** [edmundhung/conform#512]
### Describe the bug and the expected behavior

This error is appearing in 1.0.3

### Conform version

v1.0.3

### Steps to Reproduce the Bug or Issue

useEffect(() => {
      form.reset()
      }, [formData]) //from useLoaderData()

### What browsers are you seeing the problem on?

Chrome

### Additional context

If I wrap the form.reset() in a queueMicrotask the error will go away. The reason I use the formReset is that I have a form as shown below, where the items are selected in the route to the left (the list) and a detail route the right side. Using form.reset() seems to be the best way to have the form update with the newly selected item received in the detail routes useLoaderData

<img width="1089" alt="Screenshot 2024-03-11 at 5 45 52 pm" src="https://github.com/edmundhung/conform/assets/3856824/8de9d60f-6aa5-480f-a64d-34cefa5f42c8">

**Comment by JasonColeyNZ** [comment]
I am doing further testing, but it appears the form.reset() may not be needed anymore.... I had to do this in earlier version of conform to have the detail section update. I will do more testing and see if this can be removed going forwards.

**Comment by JasonColeyNZ** [comment]
OK after some quick testing, yes I do have to use form.reset() in a useEffect as the form isn't being reloaded, rather the data being updated.

**Comment by edmundhung** [comment]
Thanks for reporting. This looks like a bug from #496. I will revert it.

**Comment by edmundhung** [comment]
I have published [v1.0.4](https://github.com/edmundhung/conform/releases/tag/v1.0.4) with the problematic changes reverted for now.

**Comment by JasonColeyNZ** [comment]
Thanks mate, thank you so much for your work, and the recent ShadCN examples were perfect as well.

From: Edmund Hung ***@***.***>
Date: Tuesday, 12 March 2024 at 6:40 am
To: edmundhung/conform ***@***.***>
Cc: Jason Coley ***@***.***>, Author ***@***.***>
Subject: Re: [edmundhung/conform] flushSync was called from inside a lifecycle method (Issue #512)

I have published v1.0.4<https://github.com/edmundhung/conform/releases/tag/v1.0.4> with the problematic changes reverted for now.
