### ISSUE TITLE
Closing dialog submits form anyways.

### ISSUE THREAD

**Issue by diurivj** [edmundhung/conform#524]
## Curren behavior 
If a `Form` is inside a `Dialog` or `Modal` (I have tested just with Radix and HeadlessUI) and you close it, the `Form` would submit anyways.

## Expected behavior
Closing a modal or dialog should not trigger the `Form`

### Steps to reproduce
1. Clone this repo https://github.com/diurivj/conform-remix-dialogs
2. `npm start`
3. Open the dialog
4. Click on the input even if the dialog will `autoFocus` the input
5. Press `esc` and see the form being submitted

### Important things to know
* This does not happen with version before 1.0.0.
* This only happens using chromium (Chrome, Arc, etc). It works fine on Firefox
* The form sometimes does not submit, so you would need to test at least a couple of times, meaning this is an intermittent issue.

### Conform version

`1.0.4`

### Steps to Reproduce the Bug or Issue

1. Clone this repo https://github.com/diurivj/conform-remix-dialogs
2. `npm start`
3. Open the dialog
4. Click on the input even if the dialog will `autoFocus` the input
5. Press `esc` and see the form being submitted

### Important things to know
* This does not happen with version before 1.0.0.
* This only happens using chromium (Chrome, Arc, etc). It works fine on Firefox
* The form sometimes does not submit, so you would need to test at least a couple of times, meaning this is an intermittent issue.

**Comment by NiklasAbrahamsson** [comment]
I can confirm this, and we have also pinpointed it down to only if we have `shouldRevalidate` or `shouldValidate` set to "onBlur" 

If we set it to onSubmit or onInput the bug won't happen.

**Comment by diurivj** [comment]
Thanks for validating this, then I guess it makes sense it is _buggy_ because the dialog unmounting triggers a blur event?

**Comment by edmundhung** [comment]
Thanks for the repo and the steps! I can't reproduce the issue on my laptop (with Ubuntu) using Chromium 🤔 Would it be related to a specific OS? e.g. macos / window. 

I will give it another try tomorrow on a macos.

**Comment by diurivj** [comment]
Sorry for not being explicit about the OS, I'm using macOS `14.4 (23E214)`; even though; my coworkers tested it too, some of them use ubuntu and they got the same buggy behavior

**Comment by edmundhung** [comment]
This should be fix on [v1.0.6](https://github.com/edmundhung/conform/releases/tag/v1.0.6).

**Comment by mvirbicianskas** [comment]
@edmundhung, I've updated the library, and it seems that in combination with radix-ui the Dialog primitive, when the form is validating or revalidating based on `onBlur`, the focus target is propagated upwards the DOM tree instead of to the next input. That's probably because Dialog is "trapping" the focus and capturing it so the user's focus doesn't end up somewhere irrelevant. However if you re-focus the input, the tabbing through them works as expected. Any ideas if this is an issue in the userland or something weird going on within the `useForm` hook when it revalidates? 🤔

**Comment by theskillwithin** [comment]
@mvirbicianskas did you find a solution to this by any chance? running into similar issue
