### ISSUE TITLE
Form error won't display if there are additional buttons before the submit

### ISSUE THREAD

**Issue by garand** [edmundhung/conform#56]
I'm running into an odd bug on my form, I have buttons that aren't the submit button before the submit button in the DOM, and when they are there, the top level `form.error` will not display (set to an empty string). But if I remove those buttons, or add a hidden submit input before them, it works correctly.

https://stackblitz.com/edit/node-ygrrtp?file=app/routes/form-error-broken.tsx

I'm more than happy to provide more info to help diagnose. This is a pretty stellar library, especially for working with Remix.

**Comment by brandonpittman** [comment]
I had the same issue a few weeks ago. Adding the hidden button is the best solution to the problem.

**Comment by edmundhung** [comment]
Thanks for the stackblitz link! This is definitely a new bug to me. For now a hidden submit button / submit input should get around the issue. I will take a deeper look and get a proper fix in the next couple days.

**Comment by edmundhung** [comment]
This is fixed in [v0.4.1](https://github.com/edmundhung/conform/releases/tag/v0.4.1).
