### ISSUE TITLE
Checkbox enum array error not displaying

### ISSUE THREAD

**Issue by zaru** [edmundhung/conform#598]
### Describe the bug and the expected behavior

When using checkboxes to accept multiple values, the error message does not display when validating with `enum().array()` in Zod.

Minimal Code Example:

```ts
const schema = z.object({
  answer: z.enum(["a", "b"]).array().nonempty(),
});
```

```tsx
export function Form() {
  const [lastResult, action] = useFormState(submitAction, undefined);
  const [form, fields] = useForm({
    lastResult,
    shouldValidate: "onInput",
  });

  return (
    <form action={action} {...getFormProps(form)}>
      <fieldset>
        <legend>Please select the correct answers</legend>
        {["a", "b", "c", "d"].map((value) => (
          <div key={value}>
            <label>{value}</label>
            <input
              type="checkbox"
              name={fields.answer.name}
              value={value}
              defaultChecked={
                fields.answer.initialValue &&
                Array.isArray(fields.answer.initialValue)
                  ? fields.answer.initialValue.includes(value)
                  : fields.answer.initialValue === value
              }
            />
          </div>
        ))}
        <div>{fields.answer.errors}</div>
      </fieldset>
      <button>Submit</button>
    </form>
  );
}
```

### Conform version

v1.1.2

### Steps to Reproduce the Bug or Issue

1. Check checkboxes other than 'a' and 'b'.
2. Since values other than 'a' and 'b' are not accepted, I expect an error message to be displayed.

### What browsers are you seeing the problem on?

Chrome

### Screenshots or Videos

| empty | enum |
|--------|--------|
| ![スクリーンショット 2024-04-24 15 48 04](https://github.com/edmundhung/conform/assets/235650/6ed27027-0ca8-4b0c-92f6-8ede4535a144) | ![スクリーンショット 2024-04-24 15 48 00](https://github.com/edmundhung/conform/assets/235650/dd393a7d-bc9b-4e4e-82d4-108e6867b313) | 

The error message displays as expected when the key is `answer`.
It does not display when the key is indexed as `answer[0]`.

**Comment by edmundhung** [comment]
You can find the answer in the [discussions](https://github.com/edmundhung/conform/discussions/596#discussioncomment-9210485) question you raised.
