### ISSUE TITLE
Reflect.ownKeys(form.getFieldset()) always returns empty array

### ISSUE THREAD

**Issue by marcomuser** [edmundhung/conform#625]
### Describe the bug and the expected behavior

As stated in the title, if I call `Reflect.ownKeys(form.getFieldset())` I always get back an empty array. I would expect it to return the fields that are part of the form definition. Would it be possible to implement this via [handler.ownKeys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/ownKeys) during the Proxy creation or are there specific reasons this isn't implemented?

One of the more specific usecases: I have several form sections on a page. I want to add an indicator to each section, which displays whether the whole section has been already successfully filled or not. My initial idea was to use form.valid for this but the problem is that this property only reflects whether there are errors in the form or not. Since I validate each field `onInput`, all fields of a section are valid until the user starts typing in it, i.e. `form.valid` is true unless the user added something invalid to a field. So another approach would be to additionally iterate over the fieldset and check if each field is `!valid || !dirty`. Since I have a lot of forms I would like to do this programmatically. However, since I can't get the fieldset's `ownKeys`, I can't find a way to iterate over the fieldset.

### Conform version

v1.1.3

### Steps to Reproduce the Bug or Issue

1. Create a form with two fields with conform
2. Run `Reflect.ownKeys(form.getFieldset())`
3. Verify that the resulting array has length == 0 instead of the expected length == 2

**Comment by marcomuser** [comment]
Solved this specific issue by parsing the zod schema separately again and checking the status. I still wonder if it would be possible to retrieve the existing keys from the fieldset for further processing?

**Comment by edmundhung** [comment]
Unfortunately, Conform has no idea which fields your form has. That's why it is using a proxy with types to guide you defining each field as suggested by the type completion. It might be possible to figure it out from the zod schema, but that also depends on the complexity of the schema with no reliable way to derive it.
