### ISSUE TITLE
boolean values not being serialized correctly with intent buttons

### ISSUE THREAD

**Issue by lifeiscontent** [edmundhung/conform#638]
### Describe the bug and the expected behavior

using `form.insert.getButtonProps({name, defaultValue, index})` if the `defaultValue` has a boolean in it, it seems to be thrown away

### Conform version

v1.0.3

### Steps to Reproduce the Bug or Issue

1. create a schema with a boolean attribute (this may be something specific to a nested object, so might need to try with that)
2. use intent button API, I personally saw issues with `form.insert.getButtonProps()`
3. witness the bug by `console.log(form.value)`

### What browsers are you seeing the problem on?

Chrome

### Additional context

Let me know if you need more specifics, but these serialization bugs are rough

**Comment by jdupont22** [comment]
I've the same issue with number, when inserting a defaultValue in a array of any nested object. 

For exemple, insert a default value in an `Array<{id: number, title: string}.`

`form.insert.getButtonProps({name, {id: 3, title: 'foo'}})`

the 'title' attribute will be equals to 'foo' but the id is missing.

**Conform version**
v1.1.3
