### ISSUE TITLE
`key` is not stable on server and client

### ISSUE THREAD

**Issue by jansedlon** [edmundhung/conform#640]
### Describe the bug and the expected behavior

`key` of fieldlist is changing when on server vs on client. This causes hydration mismatches when using libraries like `@hello-pangea/dnd` because it expects the same draggableId on the server and on the client.

The workaround is to wrap the affected component on ClientOnly but this is a lucky workaround for me because it happens on initially invisible content, user has to get through tabs to get there. If it was on a place which can be seen initially, it would cause a flash

### Conform version

v1.1.3

### Steps to Reproduce the Bug or Issue
This codesandbox shows that the id on the server and on the client do not match
[codesandbox](https://codesandbox.io/p/devbox/distracted-khayyam-7mlcxy?file=%2Fapp%2Froot.tsx%3A20%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvz99br500083b6jter8mkjc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvz99br500033b6jh8h22gx8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvz99br500053b6j17bjfz81%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvz99br500073b6j89g4zesb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvz99br500033b6jh8h22gx8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz99br500023b6ji8upd52b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Froot.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A36%257D%255D%257D%252C%257B%2522id%2522%253A%2522clwel0vuo00023b6jyxmsr48g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A37%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A37%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Froutes%252Ftodos.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwel9c7600023b6pd9g1csbg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A31%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A31%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvz99br500033b6jh8h22gx8%2522%252C%2522activeTabId%2522%253A%2522clvz99br500023b6ji8upd52b%2522%257D%252C%2522clvz99br500073b6j89g4zesb%2522%253A%257B%2522id%2522%253A%2522clvz99br500073b6j89g4zesb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz99br500063b6jiuxjaz2k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Ftodos%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvz99br500063b6jiuxjaz2k%2522%257D%252C%2522clvz99br500053b6j17bjfz81%2522%253A%257B%2522id%2522%253A%2522clvz99br500053b6j17bjfz81%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz99br500043b6jdukudvpv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520%2540hello-pangea%252Fdnd%2522%252C%2522id%2522%253A%2522clvz9a9bi005z3b6jlta5jn7n%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvz99br500043b6jdukudvpv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### What browsers are you seeing the problem on?

Chrome

### Screenshots or Videos

<img width="829" alt="image" src="https://github.com/edmundhung/conform/assets/13948180/803eaa35-4f9c-4c98-bc7f-72f339e0f60d">

**Comment by edmundhung** [comment]
The `field.key` provided is only used for React element and so it is not stable as you said. I am not familiar with the library you are using but maybe you can use `field.id` instead if you are looking for a stable id.

**Comment by jansedlon** [comment]
I **think** the drag and drop library remounts the components. Is it possible that the ids then change? If i switch over to `field.id`, after first drag and drop it complains that the id was not found.

**Comment by jansedlon** [comment]
Okay I hate this. Seems like both `key` and `draggableId` must be `field.id` and then it seems like it works. I'm really sorry Edmund for your wasted time.
