### ISSUE TITLE
When using multiple forms on a page with useFetcher, some forms are left stuck showing old value

### ISSUE THREAD

**Issue by WhoAteDaCake** [edmundhung/conform#663]
### Describe the bug and the expected behavior

The forms show old value even if the props are updated.
Bellow is the example from the strackblitz repo:

![image](https://github.com/edmundhung/conform/assets/16735813/cbfb7687-83c1-44e3-867a-7b29746ac40b)

### Conform version

v1.1.4

### Steps to Reproduce the Bug or Issue

1. https://stackblitz.com/edit/remix-run-remix-x7ycx9?file=app%2Froutes%2F_index.tsx
2. Try and modify the title of the first entry (had to do it a few times), after submit, the value of the title won't match "Actual title"

### What browsers are you seeing the problem on?

Chrome

**Comment by WhoAteDaCake** [comment]
It's an odd situation, since it happens almost at random. Sometimes straight away, sometimes i need to try it a few times

**Comment by WhoAteDaCake** [comment]
@edmundhung I don't think that the proposed solution works?

I've implemented it here: https://stackblitz.com/edit/remix-run-remix-t1vfze?file=app%2Froutes%2F_index.tsx but it still shows old data

```typescript
  const fetcher = useFetcher<typeof action>();
  const formId = `my-form-${id}`;
  const navigation = useNavigation();
  const [form, fields] = useForm({
    id: formId,
    constraint: getZodConstraint(contentSchema),
    defaultValue: {
      title,
      description,
      id: String(id),
    },
    lastResult: navigation.state === 'idle' ? fetcher.data?.result : null,
    onValidate({ formData }) {
      return parseWithZod(formData, { schema: contentSchema });
    },
    shouldRevalidate: 'onInput',
  });
```

**Comment by edmundhung** [comment]
You are quick! Just waiting the docs site to be updated before comment it here. You just need to change it to wait for the fetcher state: `lastResult: fetcher.state === 'idle' ? fetcher.data?.result : null,`

**Comment by WhoAteDaCake** [comment]
That does work! Great stuff! Hopefully with the new documentation, people spend less time than I did trying to figure out why this was happening :D.

Appreciate your help!
