### ISSUE TITLE
[1.1.0] `resetForm: true` doesn't reset `unstable_useControl` values

### ISSUE THREAD

**Issue by halljus** [edmundhung/conform#673]
### Describe the bug and the expected behavior

As of Conform v1.1.0 (and through v1.1.4), resetting the form doesn't seem to reset `unstable_useControl` values (unless, possibly, it's the only field in the form - see repro).

### Conform version

v1.1.4

### Steps to Reproduce the Bug or Issue

https://stackblitz.com/edit/remix-run-remix-pvh5h7?file=app%2Froutes%2F_index.tsx

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by edmundhung** [comment]
I think I know the issue. I will try to get a fix out asap. Thanks!
