### ISSUE TITLE
One Page MultiStep Doesn't Retain Values

### ISSUE THREAD

**Issue by jtan80813** [edmundhung/conform#693]
### Describe the bug and the expected behavior

I'm using `Conform` and [Shadcn Stepper](https://shadcn-stepper.vercel.app/) to build a multi-step form, and running into a similar issue with repopulating form fields when navigating back to previous steps,

### Conform version

v1.1.4

### Steps to Reproduce the Bug or Issue

 You can check out the code on CodeSandbox: 
 https://codesandbox.io/p/devbox/conform-with-shadcn-stepper-fxl9sz

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari, Others

**Comment by edmundhung** [comment]
Conform does not persist any form value. You can either keep the submitted value in a database, a cookie or even in the document by rendering the inputs on the previous step again but making them visually hidden.
