### ISSUE TITLE
resetForm: true resets status

### ISSUE THREAD

**Issue by lifeiscontent** [edmundhung/conform#756]
### Describe the bug and the expected behavior

I'm not sure if I'm misunderstanding, but I have a scenario where if the form submission was unsuccessful I want to keep a form drawer open, so my plan was to check the submission status, and if it wasn't equal to `success` keep the form drawer open so the user can take care of the errors

it appears that when we return `json(submission.reply({resetForm: true}))` it actually clears out the status, how can I be sure that the submission was successful?

### Conform version

v1.1.5

### Steps to Reproduce the Bug or Issue

1. Create a Form Drawer
2. use a fetcher
3. in the action do what I described above
4. see that if the action was successful the status is not defined in the `fetcher.data`

**Comment by Garajluc** [comment]
Any updates on this?

**Comment by lifeiscontent** [comment]
@Garajluc yes, but what's your use case? I can give some guidance depending on what you need because it'll vary depending on what your expected outcome is.

**Comment by Garajluc** [comment]
Thank you for your response, I actually read through similar issues within the conform repository and I think I understand it better now, so no need for additional guidance at this moment. Thank you again :)
