### ISSUE TITLE
How to use with input type radio elements?

### ISSUE THREAD

**Issue by snrmwg** [edmundhung/conform#79]
When I use the library like this:

    <label>
          <div>Answer<div>
          <input value="a" {...conform.input(answer.config, {type: 'radio'})}/> A
          <input value="b" {...conform.input(answer.config,{type: 'radio'})}/> B
          <div className="field-error">{answer.error}</div>
     </label>

I get the error message `Entry with the same name is not supported`.

How am I supposed to use validation for this case?

**Comment by edmundhung** [comment]
> I get the error message `Entry with the same name is not supported`.

Any chance you have another input with the name `answer`? Your [example](https://codesandbox.io/s/conform-radio-buttons-example-41u5rl?file=/src/App.tsx) works fine for me.

It would be great if you can provide a sandbox that reproduce the issue. Thank you!

**Comment by snrmwg** [comment]
These two inputs are the only one with that name.

I'm using it within a Remix project. And I would like it to work also with disabled Javascript / client side validation and instead server side validation (but that is not reason for message I think).

I provided the repo here:

https://github.com/snrmwg/remix-form-app

And I tried to execute it as a sandbox:

https://codesandbox.io/s/github/snrmwg/remix-form-app

But it doesn't seem to start :(

You can start the project locally as every other remix project. Does that help?

**Comment by snrmwg** [comment]
I just posted a small fix for my demo project and it seems to work now ... I need to take a deeper look tomorrow, but there is a great chance that the problem was me and not the lib.

**Comment by edmundhung** [comment]
> I just posted a small fix for my demo project and it seems to work now ... I need to take a deeper look tomorrow, but there is a great chance that the problem was me and not the lib.

I am glad that it works now 😄 One tips: Do not call `event.preventDefault()` if you are using Remix, it will prevent it from submitting the form for you. You can remove the whole `onSubmit` handler there.

**Comment by snrmwg** [comment]
OK. Thanks for the hint.

By the way: in this demo I send a "form level" error message when server validation is executed. For simplification I send it always. It get's displayed correctly above the form. But when I step through the form it disappears.

How can I get a persistent form level error message from the server side validation?

**Comment by snrmwg** [comment]
Oh it seems that it stays persistent as soon as I removed the `onSubmit` handler?

**Comment by edmundhung** [comment]
> Oh it seems that it stays persistent as soon as I removed the `onSubmit` handler?

Yep. The problem was caused by `event.target.submit()` which triggers native browser submission and refresh the whole page.
