### ISSUE TITLE
How to perform async client side action after validation and before submit?

### ISSUE THREAD

**Issue by snrmwg** [edmundhung/conform#80]
I need to integrate Recaptcha check to my forms. I thought best way would be to perform that after validation and it needs to be done before submission. Steps are like this:

a) validate form using conform
b) perform async recaptcha call and get token
c) integrate token value to form data to be submitted together with other validated value

I'm struggling how to perform steps b+c ideally.

**Comment by edmundhung** [comment]
> I need to integrate Recaptcha check to my forms. I thought best way would be to perform that after validation and it needs to be done before submission. Steps are like this:
> 
> a) validate form using conform b) perform async recaptcha call and get token c) integrate token value to form data to be submitted together with other validated value
> 
> I'm struggling how to perform steps b+c ideally.

Maybe take a look of #50 and see if it helps. Note that Recaptcha does not work without JS (as far as I have heard) and so your action will not receive the token if JS is disabled.

**Comment by snrmwg** [comment]
Thanks for the reference, I didn't see it before. That's exactly the same problem and the solution works for me.
