### ISSUE TITLE
Site is showing 404.

### ISSUE THREAD

**Issue by CodingAleCR** [edmundhung/conform#809]
### Describe the bug and the expected behavior

<img width="1512" alt="Screenshot 2024-10-26 at 10 07 41 PM" src="https://github.com/user-attachments/assets/a67e0c4d-3ac7-43d6-a037-73b2043fdf4d">

### Conform version

v1.2.2

### Steps to Reproduce the Bug or Issue

Just access the page & docs.

**Comment by edmundhung** [comment]
It should be up now. I didn't notice the github token is just expired. Thanks for reporting!
