### ISSUE TITLE
Idea: provide "inProgress" state of form

### ISSUE THREAD

**Issue by snrmwg** [edmundhung/conform#82]
Would like to know what you think about that idea:

The form could provide some kind of "inProgress" state while validation and submission. That could be used to disable submit button during that phase:

    <form method="post" {...form.props}>
        [...]
         <button
            type="submit"
            className={cx('btn', 'btn-item', form.inProgress() && 'loading')}
            disabled={form.inProgress()}
          >Submit</button>
    </form>

I could provide a PR for that if you like...

**Comment by edmundhung** [comment]
Conform take cares of the validation only. The submission is fully handled by Remix. Checking `navigation.state === 'submitting'` should be enough.

**Comment by edmundhung** [comment]
To add a bit of context here: Client validation is done on the submit handler (i.e. `form.props.onSubmit`). The idea is basically calling `event.preventDefault()` when there is any error found.

**Comment by snrmwg** [comment]
My idea would probably combine `conform` too much with Remix. 

I have the need to implement the `onSubmit` handler asynchronously (which is possible). And I want to have the in "in processing" state both during validation and during `onSubmit`. In a particular form, I can also do that by using `useState()` and implementation in `onValidate` and `onSubmit` handlers. But that has a small gap between the calls for one thing. And I would have to implement it repeatedly for each form. So I was thinking of a flag directly on the form.

Do you have any idea how to implement it reusable without deep integration in conform?

**Comment by edmundhung** [comment]
I would be interested to know more what you are trying to do with an async submit event handler. If it is used for async validation, have you tried the approach mentioned [here](https://conform.guide/validation#async-validation)?

**Comment by snrmwg** [comment]
I updated my demo project to use the `server-validation` mode of `useForm`. Now I understand it somehow better.

You can find my demo project here: https://github.com/snrmwg/remix-form-app

It's a simple remix project with a very contrived and slow validation and handing logic (`app/routes/index.tsx`) . But you can see usage of `formHandlingInProgress` managed by useState() and `transition.state === 'submitting'`.

My hope is that management of this state could somehow be more centralised?

**Comment by brandonpittman** [comment]
Check out the global pending state hooks in Remix Utils. Might be helpful.

**Comment by edmundhung** [comment]
I have tried your demo. In general we should move all async logic to the server and Conform's server validation should make it seamless. But captcha is one of the exception that couldn't be done on the server. What missed from the `transistion.state` is the time when you are running the captcha.

```ts
const isLoading = transition.state === 'submitting' || isCaptchaRunning;
```

How about creating a simple hook to manage the loading state of the captcha?

```tsx
function useCaptcha() {
  const [isRunning, setIsRunning = useState(false);
  const runCaptcha = async (timeoutMillis: number) => {
    setIsRunning(true);
    const token = await captcha(timeoutMillis);
    setIsRunning(false);

    return token;
  };
  return [isRunning, runCaptcha] as const;
}
```

Usage:
```tsx
export default function Example() {
  const state = useActionData<typeof action>()
  const submit = useSubmit()
  const transition = useTransition()
  const [isCaptchaRunning, runCaptcha] = useCaptcha();
  const form = useForm({
    mode: 'server-validation',
    state: state,
    onValidate({ form, formData }) {
      // ...
    },
    async onSubmit(event, { submission, formData }) {
      if (submission.type === 'validate' && (submission.intent !== 'field2' || hasError(submission.error, 'field2'))) {
        event.preventDefault();
      } else if (submission.type === 'submit') {
        event.preventDefault();

        const form = event.target as HTMLFormElement
        formData.set('captcha', await runCaptcha(5_000))

        // Maybe Conform should also provide the method and action for you
        // This setup ignore the cases when the submitter has a `formMethod` or `formAction` attribute
        submit(formData, { method: 'post', action: form.getAttribute('action') ?? form.action })
      }
    },
  })

  return (
    <Form method="post" {...form.props}>
        {/* ... */}
        <button type="submit" disabled={isCaptchaRunning || transition.state === 'submitting'}>Post!</button>
      </Form>
  )
}
```

I will think about if there is any good integration Conform can do for you. I might also create a `@conform-to/remix` package in the future that provide tighter integration with Remix.

**Comment by snrmwg** [comment]
Your provided way feels good. `@conform-to/remix` also a nice idea ... For me nothing more to do in this issue.

**Comment by ivan-kleshnin** [comment]
What is `transition.state`? 👀  React's `const transition = useTransition()` returns a tuple, not an object with `state`.

**Comment by edmundhung** [comment]
We were referring to a hook from Remix that is now renamed to [useNavigation](https://remix.run/docs/en/main/hooks/use-navigation).
