### ISSUE TITLE
Disabled field's value is not preserved

### ISSUE THREAD

**Issue by wonu** [edmundhung/conform#833]
### Describe the bug and the expected behavior

I have a form with an `isFree` checkbox and a `price` field.
The `price` field should be disabled and excluded from form submission based on the `isFree`.
Also the `price` value is used in other places and should be preserved.
However, when toggling `isFree`, the `price` value disappears and then reappears.
I'm not sure if this is a bug, but I'm wondering if there are any other ways to achieve this.

### Conform version

v1.2.2

### Steps to Reproduce the Bug or Issue

Simple repro: [https://stackblitz.com/edit/vitejs-vite-8zxcaa?file=src%2FApp.tsx&terminal=dev](https://stackblitz.com/edit/vitejs-vite-8zxcaa?file=src%2FApp.tsx&terminal=dev)

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by edmundhung** [comment]
It seems correct to me to use the `disabled` attribute if you want to exclude it from form submission. Are you trying to access the value of the price field after it is disabled? (e.g. `fields.price.value`)? Conform field value always reflects the result of the FormData API which ignores all disabled fields. Maybe you should make the price field controlled, then you will have access to the price value.

**Comment by wonu** [comment]
Ah, I thought that since getting the value via DOM access works even when disabled, `fields.price.value` would also work.
As you suggested, I'll try solving it with a controlled input or ref.
Thank you.
